### ISSUE TITLE
It works on laravel 5.2?

### ISSUE THREAD

**Issue by Asetss** [Nayjest/Grids#101]
Hi. I updated laravel 5.1 on 5.2. All works well except grid.

I receive an error.

FatalErrorException in GridInputProcessor.php line 40:
Class 'Input' not found

In what may be the problem?  Maybe it is necessary to correct the error

**Comment by Nayjest** [comment]
Hi!
Should work.

Do you have \Input class alias in your app config?

```php
 'aliases' => [
...
'Input' => 'Illuminate\Support\Facades\Input',
...
]
```

Try to replace
```php
use Input;
```
to
```php
use Illuminate\Support\Facades\Input;
```
in GridInputProcessor.php

**Comment by Asetss** [comment]
It's worked. Sorry.

**Comment by josemiguelramirez** [comment]
thank you !!
