### ISSUE TITLE
Select filter with main query's where input

### ISSUE THREAD

**Issue by XaphanBael** [Nayjest/Grids#102]
I have select filter which gets a list of all sales executives through a method in the model.
```
->addFilter(
   (new SelectFilterConfig)
       ->setOptions((new Opportunity)->getSalesExecutives())
)
```
This method looks like this:
```
    public function getSalesExecutives()
    {
        $salesExecutiveList = DB::table('opportunities')
            ->distinct()
            ->orderBy('created_by_app_user_abbr', 'ASC')
            ->lists('created_by_app_user_abbr', 'created_by_app_user_abbr');

        return $salesExecutiveList;
    }
```

This return a list of all the sales executives, but is it possible to filter this even further by feeding the method the where parameter from the final query.

So let's say my other filters include a country and date from/till datepicker. Instead of showming me all 30 sales executives existing in the total table, now i only want to show the three sales executives that are displayed after applying the filter. Is this possible, and if so how do i do it.

**Comment by Nayjest** [comment]
Hi!
If I understand correctrly, you want to implement linked filters. 
Example: regions and cities.
Then for showing correct cities, just read region from $_GET in controller and pass to method that returns cities for select. To get selected region server-side in $_GET, you may add javascript that will submit grid form each time when regions select will be changed (onchange event).

**Comment by Nayjest** [comment]
Please let me know if it works for you.

**Comment by SuperDicq** [comment]
I found a way to do this without adding any javascript yourself, but using the ```setSubmittedOnChange()``` method and passing the request to the model.

It would look something like this:
```->addFilter(
   (new SelectFilterConfig)
       ->setOptions((new Opportunity)->getSalesExecutives(\Request::input()))
       ->setSubmittedOnChange(true)
)
```

In the model the method would look like this:
```
public function getSalesExecutives($request)
    {
        $salesExecutiveList = DB::table('opportunities')
            ->distinct();

        if(!empty($request['GridName']['filters']['field-eq'])) {
            $salesExecutiveList = $salesExecutiveList->where('created_by_app_user_abbr, $request['GridName']['filters']['field-eq']);

        $salesExecutiveList = $salesExecutiveList->orderBy('created_by_app_user_abbr', 'ASC')
            ->lists('created_by_app_user_abbr', 'created_by_app_user_abbr');

        return $salesExecutiveList;
    }
````

**Comment by Nayjest** [comment]
Oh, I forgot about 'setSubmittedOnChange' method. 

Nice solution. Thanks.

I'm closing this issue.
