### ISSUE TITLE
setSubmittedOnChange() for DateRangePicker

### ISSUE THREAD

**Issue by SuperDicq** [Nayjest/Grids#103]
Is there a possibility of adding a method similar setSubmittedOnChange() of SelectFilterConfig to the DateRangePicker class?

I want the grid to update immediately after selecting the date range, without having to click on refresh.

**Comment by Nayjest** [comment]
Yep. If you want to implement is as soon as possible, I will appreciate if you will do it yourself & create pull request. Than I will check changes, accept it and publish new grids release.

**Comment by Nayjest** [comment]
Released in [v0.9.12](https://github.com/Nayjest/Grids/releases/tag/v0.9.12)
