### ISSUE TITLE
Fixed column width

### ISSUE THREAD

**Issue by SuperDicq** [Nayjest/Grids#114]
Is there a way to manually set widths for a column?

For example:
* being able to set a minimum width so the column doesn't get too small even if the values are small or empty.
* being able to set a maximum width in a column so values that are too long will wrap to the next line, increasing the height of the cell.

If there is not a way you can turn this into a feature request. If that is the case I might implement it myself if I have the time for it at work.

**Comment by wdog** [comment]
see #85

**Comment by SuperDicq** [comment]
That's a nice solution for now, however I'm still going to suggest to implement methods like `setMinimumWidth()` and `setMaximumWidth()` to FieldConfig.

**Comment by wdog** [comment]
```php
(new FieldConfig)
  ->setName('name')
  ->setLabel('User Name')
  ->setSortable(true)        
  ->setWidth('100px')
  ...
```

adding getter/setter methods in FieldConfig.php

```php
protected $columnWidth;
public function setWidth($width)
{
  $this->columnWidth = $width;
  return $this;
}

public function getWidth()
{
  return $this->columnWidth;
}

```

and finally changing `TableCell.php`

```php
public function getAttributes()
{
        if (empty($this->attributes['class'])) {
            $this->attributes['class'] = 'column-' . $this->getColumn()->getName();
        }
        if ($this->column->isHidden()) {
            $this->attributes['style'] = 'display:none;';
        }
        if( $w = $this->column->getWidth()){
            $this->attributes['style'] .= "width:{$w};";
        }
        return $this->attributes;
}
```

but probably is better to add a generic attribute to add some style.

please let me know if can help

**Comment by Nayjest** [comment]
Why just not write CSS for .column-\<your_column-name\> class? (Grids package adds this class to table cells by default)

Adding methods like setMaximumWidth to FieldConfig is not a best idea, becouse there is hundreds of CSS properties that can be useful there.

> but probably is better to add a generic attribute to add some style.

Or even generic attribute to add HTML tag attributes (TableCell already supports adding custom html attributes)

**Comment by wdog** [comment]
I agree, but sometimes is easier to write code in one place rather than write php and css, if there are different columns called `.column-username` for example I must load different css files.

adding custom class maybe is the best solution

**Comment by getcrud** [comment]
maybe add width in header column in thead. it applied to all row in tbody
