### ISSUE TITLE
Weird formatting from ColumnsHider

### ISSUE THREAD

**Issue by hackel** [Nayjest/Grids#115]
This is what it looks like when I click on the ColumnsHider component I added:
![screenshot from 2016-01-27 13-18-28](https://cloud.githubusercontent.com/assets/583677/12625351/16bd9d98-c4f9-11e5-89eb-91a3882fe5cb.png)
There is probably a conflict with some CSS I am using, which I'm going to investigate now.  Some of the component CSS might need to be defined more explicitly to avoid this.

**Comment by hackel** [comment]
This was caused by an `input {width: 70%}` in my CSS.  I just had to add `input[type="checkbox"] {width: unset}' to fix it.  This seems specific enough to my site that it's not an issue for the package.

**Comment by Nayjest** [comment]
It happens :)
