### ISSUE TITLE
How to use PHP Array as Data Provider

### ISSUE THREAD

**Issue by asaf050** [Nayjest/Grids#119]
Hey,

This is not a real issue, I just can't figure out how to use PHP Array as my grid's data provider...
Can someone please help me out?

Thanks!

**Comment by Nayjest** [comment]
Hi
There is pull-request with such feature: https://github.com/Nayjest/Grids/pull/118
But it's not merged yet. You can use that code on your own risk.

**Comment by Nayjest** [comment]
There is alot of issues in mentioned pull-request, I'm not sure that will merge it, so generally I would recommend to use [view-components/grids](https://github.com/view-components/grids) for this purpose (It's next major release with alot of backward-incompatible changes moved to separate repository, but moyou can start to use it in parallel with nayjest/grids package).
