### ISSUE TITLE
Record counts

### ISSUE THREAD

**Issue by sandip-mane** [Nayjest/Grids#12]
How do i show following output in footer or header?
"Showing 1-50 of 10000"
possible?

**Comment by icemanblas** [comment]
Hi,

I'm using the component, but the output is "Showing records of", so the 'from', 'to' and 'total' numbers are not shown. I'm using Laravel 5.0, and using the component like this:

`(new ShowingRecords)`

Any suggestions are apreciated. Thanks in advance.
