### ISSUE TITLE
Method Nayjest\Grids\Grid::__toString() must not throw an exception

### ISSUE THREAD

**Issue by TBarina** [Nayjest/Grids#121]
I cannot make it work on Laravel 5.2
Keep getting Method Nayjest\Grids\Grid::__toString() must not throw an exception

**Comment by TBarina** [comment]
Sorry, my fault. I had to clear bootstrap/cache in order to have it working.

**Comment by Nayjest** [comment]
Hi!
To avoid situations that's hard to debug becouse of impossibility to throw exception from code behind __toString, dont convert grid to string, always call render()
Example of view file:

```php
<h1>My Report</h1>
<?= $grid ?>
```

Replace to:
```php
<h1>My Report</h1>
<?= $grid->render() ?>
```
