### ISSUE TITLE
dropdown in grid's filter

### ISSUE THREAD

**Issue by rifaniponk** [Nayjest/Grids#123]
I didnt find any example of dropdown in grid's filter. is it possible to achieve it?
it would be great if we can use dropdown in grid's filter.

thank you

**Comment by Nayjest** [comment]
Hi,
It's possible, see SelectFilterConfig

**Comment by wdog** [comment]
An example maybe helps

```php

     (new FieldConfig)
            ->setName('tableField') // grid values
            ->setLabel('Table Label') // label name
            ->setSorting(Grid::SORT_ASC) // default order
            ->setSortable(true) // sortable field using tableField field
            ->addFilter(
              (new SelectFilterConfig)
                ->setName('tableFieldFilter')
                ->setSubmittedOnChange(true) // on change submit request
                ->setOptions([]) // array of possibile values in filter
            ),
```

**Comment by Nayjest** [comment]
@wdog Thanks for submitting example!
@rifaniponk I'm closing this issue. If you have another questions, submit it in separate issues.

Also, try [vew-components/grids](https://github.com/view-components/grids) with [eloquent-data-processing](https://github.com/view-components/eloquent-data-processing), new grids is almost ready for release, I already use it on production. See usage examples: 
https://github.com/view-components/grids/blob/master/tests/webapp/Controller.php

**Comment by rifaniponk** [comment]
@Nayjest @wdog cool. it's works like a magic.
thanks for your support
