### ISSUE TITLE
how to access another field value in setCallback()

### ISSUE THREAD

**Issue by rifaniponk** [Nayjest/Grids#124]
Hi. 
I'm going to create action button (edit & delete) in column action. So I added additional column `action` using this way: 
```php
new FieldConfig('id'),
(new FieldConfig)
   ->setName('action')
   ->setLabel('Action')
   ->setCallback(function ($val) {
       return '<a href="user/edit/<id>">edit</a>';
   })
```  

my question is
how I can get value `id` in `setCallback()` since it's on another field?

any help would be helpful

**Comment by wdog** [comment]
use something like this 

```php

->setCallback(function ($val, ObjectDataRow $row) {
  $data = $row->getSrc();           
  return link_to_route('user.show', $val, [$data->id]);
}),

```

**Comment by Nayjest** [comment]
@wdog, thanks for supporting community.
@rifaniponk I'm closing this issue, if you have another questions, create separate issues.

**Comment by rifaniponk** [comment]
@wdog @Nayjest coool!
thanks for your help. highly appreciated!
