### ISSUE TITLE
Datepicker can't handle 2016-04-01

### ISSUE THREAD

**Issue by XaphanBael** [Nayjest/Grids#125]
I'm not sure why or how, but my grids has a datepicker filter, which can't handle a row with 2016-04-01 as a date. When i change the date of that row to either 2016-03-31 or 2016-04-02 it works just fine.

Upon loading the 2016-04-01 date, firefox plugin firebug shows the following error in the console:

TypeError: $ is undefined
$.fn.daterangepicker = function (options, cb) {

Also the page is missing all styling, just a white page, with the data it already loaded up untill the error with the date it can't handle, which would also explain the above error.

**Comment by Nayjest** [comment]
Looks like problem in jQuery, it doesn't loaded. Do you use CDN for jquery or it's on your server? Maybe there is some problems with CDN or internet connection?

**Comment by XaphanBael** [comment]
The thing is, the jQuery gets loaded when the page is finished, since grids or carbon or datepicker can't handle 2016-04-01, it stops rendering the page, and thereby the jQuery also doesn't get loaded.

**Comment by Nayjest** [comment]
Looks like real PHP error isn't displayed.
First of all, check page source from browser, maybe error is printed to place where it can't be displayed.

If there is no error, try tyemporary turn on error reporting & displaying in your index.php:
```php
error_reporting(E_ALL); 
ini_set("display_errors", 1); 
```

Or use xDebug to locate error.

**Comment by XaphanBael** [comment]
I tried that on my localhost (wamp), and it complained about reachting the max nested level of 100, when i could increase it till about 430, higher than that my browsers would reset the connection.

So it looks like either an unending recursive function, or a memory leak triggered by a date of 2016-04-01

**Comment by Nayjest** [comment]
1. Check laravel log & php log for errors
2. If you use laravel debug_bar, you can see SQL query generated by grid, try to reproduce that query unig target Eloquent model

**Comment by XaphanBael** [comment]
1. The logs are empty
2. Since the page stops rendering, the debugbar is not loaded.

However, something strange is happening, i had this "bug" on two different grids, on both grids, a data of 2016-04-01 caused it to malfunction, however in one of the db tables i re-populated the data, and that grid is now working with 2016-04-01 like nothing happened, whilst the other grid is still bugged.

**Comment by Nayjest** [comment]
So will you try to find a source of problem or just re-populate DB?
If you will continue research, please, keep me informed becouse if I can do something on Grids side that will prevent same errors or at least prvide more debug information, I would like to do that.

Another suggestion: look at your DB records with date equal to 2016-04-01. Perhaps some of this  records differs from another and it cause an error (for example, there is some empty fields or you use Eloquent model relations and there is no corresponding record in related table, etc.)

**Comment by XaphanBael** [comment]
I will try to find the problem, since repopulating the live site is to big of a hassle, but i'm not quite sure where to look next, the datepicker is bound to a create_date filed on the databaase, and the only thing i have to change to make it work is changing 2016-04-01 to for instance 2016-04-02, so i highly doubt it has to do with empty fields or character encoding.

**Comment by XaphanBael** [comment]
It seems i found the issue, my intern made a custom extension to handle currency rates, and the fault was in there, weird that i did not see any errors though, but by commenting out piece for piece i narrowed it down to the problem. Thanks for your support though!

**Comment by Nayjest** [comment]
No problem )
