### ISSUE TITLE
How can I add images in my table

### ISSUE THREAD

**Issue by Gregomexl** [Nayjest/Grids#126]
I have a question, what is the code to add a url_img as a "Image" in my table like <td><img /><td>

best

**Comment by Nayjest** [comment]
Example: 
```php
(new FieldConfig)
                        ->setName('img')
                        ->setLabel('Image')
                        ->setCallback(function ($val) {
                            return "<img src='{$val}'/>";
                        })
```
If image URL is not in current column, you can get $row object from second argument of callback and extract value you need.

**Comment by Nayjest** [comment]
See https://github.com/Nayjest/grids-demo/blob/master/app/Http/Controllers/DemoController.php for more examples

**Comment by Gregomexl** [comment]
Thanks, and another question is how can I use conditionals, like if, while, for. etc. You need some kind of syntax? for example if I dont want to show a particular row with a certain id.

best

**Comment by Nayjest** [comment]
See examples in link above
