### ISSUE TITLE
Excel desconfigurate

### ISSUE THREAD

**Issue by jrglaber** [Nayjest/Grids#128]
Hi, excel exporter is generating the entire spreadsheet unconfigures, what can be?

[print here](https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/13133281_982769998437984_2539941194439101369_n.jpg?oh=68e5f4512aeadc9fe40012356a9dccb2&oe=57E057AF)

**Comment by Nayjest** [comment]
Hi!
This issue must be addressed to [maatwebsite/excel](https://github.com/Maatwebsite/Laravel-Excel) package author. 

All code from nayjest/grids, related to excel export here: https://github.com/Nayjest/Grids/blob/master/src/Components/ExcelExport.php

If you will create issue in maatwebsite/excel issue tracker, please share link in comment here.
