### ISSUE TITLE
Change Delimiter

### ISSUE THREAD

**Issue by hurbanores** [Nayjest/Grids#130]
Hello!

I have a trouble with the csv delimiter and i want to change the default value ';' to ','

How i do that?

Thank you

**Comment by wdog** [comment]
I think that you can just create your own class that extends `CsvExport` and define your separator

```php
class MyCsvExport extends CsvExport{
    const CSV_DELIMITER = ',';
}
```

maybe there's a better method but I don't know :smile:

**Comment by Nayjest** [comment]
Yep, it's required to create custom class.
Further grids versions ([view-components/grids](https://github.com/view-components/grids)) has  [setCsvDelimiter() method](https://github.com/view-components/grids/blob/master/src/Component/CsvExport.php#L87).
