### ISSUE TITLE
RecordsPerPage not work in L5.1

### ISSUE THREAD

**Issue by bakhtari** [Nayjest/Grids#133]
(new thead)
            ->setcomponents([
                (new columnheadersrow),
                (new filtersrow)
                ,
                (new onecellrow)
                    ->setrendersection(renderableregistry::SECTION_END)
                    ->setcomponents([

                        new columnshider,
                      >>>  (new RecordsPerPage)
                            ->setVariants([
                                50,
                                100,
                                1000
                            ]),
                      

not work

**Comment by wdog** [comment]
try simply 

```php
    (new THead)
        ->setComponents([
            (new OneCellRow)
            ->setComponents([           
                (new RecordsPerPage)
               ->setVariants([10,100,500,1000])
            ])
        ->setRenderSection(THead::SECTION_BEGIN)
        ....
```

**Comment by wdog** [comment]
And please for all of you read how to post code [https://guides.github.com/features/mastering-markdown/](url)

**Comment by Nayjest** [comment]
@wdog thanx for support!

@bakhtari does it helps? Can we close issue?

**Comment by bakhtari** [comment]
Tnx your solution is ok
