### ISSUE TITLE
How to use Nayjest Tree, any examples?

### ISSUE THREAD

**Issue by brigite** [Nayjest/Grids#134]

**Comment by Nayjest** [comment]
Hi!
See tests https://github.com/Nayjest/Tree/tree/master/tests

**Comment by Nayjest** [comment]
Also, just see sources of ParentNodeTrait & ChildNodeTrait, there are phpDoc comments.
https://github.com/Nayjest/Tree/blob/master/src/ParentNodeTrait.php
https://github.com/Nayjest/Tree/blob/master/src/ChildNodeTrait.php

If you want, you can help with documentation =)
