### ISSUE TITLE
Can I change the default order field?

### ISSUE THREAD

**Issue by pascualm4** [Nayjest/Grids#141]
I have an issue when I pass the QueryBuilder variable to the grid. The QueryBuilder have a join statement and trigger the following database error:

SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in order clause is ambiguous (SQL: select * from `actions` inner join `sections` on `actions`.`section_id` = `sections`.`id` and `sections`.`institution_id` = 1 order by `id` asc limit 10 offset 0)

The QueryBuilder is ok.

Thanks in advance

**Comment by Nayjest** [comment]
Hi!
Few thoughts:
a) Try to define alias for selected field  in query builder and use it as column name (SELECT table1.is as main_id)
b) If this doesn't helps, override Sorter class & Grid::getSorter() method
c) If a) does not work and if you will find solution that is more simple than [c], please share it.

**Comment by wdog** [comment]
Hoping to have understood your problem I'll leave my opinion

this is your query

```sql
select * 
from actions 
join sections 
on actions.section_id = sections.id
```

the problem is that you must define all fields on your select one by one. 
**it is a good practice to never use *.**

if you write  one only field named **id** everything works fine

```sql
select 
  actions.id
, actions.name 
, sections.field1
, sections.field2
from actions 
join sections 
on actions.section_id = sections.id
```

**Comment by pascualm4** [comment]
Thanks for your replies.
Make some aliases and override the function getSorter() both works well!

I only apply the aliases.

Best regards.
