### ISSUE TITLE
Can I pass an Illuminate\Database\Eloquent\Collection element to the EloquentDataProvider?

### ISSUE THREAD

**Issue by pascualm4** [Nayjest/Grids#142]
I have an application which calls an api and get an Illuminate\Database\Eloquent\Collection element to render in the view.

I just want apply the filters over that collection but when I pass that element the app trigger the following error: 

Argument 1 passed to Nayjest\Grids\EloquentDataProvider::__construct() must be an instance of Illuminate\Database\Eloquent\Builder, instance of Illuminate\Database\Eloquent\Collection given

I know the error but doesn't have any other way to get the data because the database are remote.

Do you have any idea to solve that issue?

**Comment by Nayjest** [comment]
Upd: to use view-component/grids with eloquent, include [view-components/eloquent-data-processing](https://github.com/view-components/eloquent-data-processing) package.

Upd2: I think, in your case the simplest solution is to try to work via Eloquent QueryBuilder if its possible.

If your api calls are just a method calls to 3rd-party classes, there is a sense to override api class &
replace
```php
// inside some api method
return $queryBuilder->get();
// or return $queryBuilder->paginate();
```
to
```php
return $queryBuilder;
```

**Comment by pascualm4** [comment]
The Upd2 doesn't work because cannot transform the builder object to a string from the api. 

I will check the view-components/eloquent-data-processing and the view-components/grids. Hope that works.

**Comment by Nayjest** [comment]
Hi @pascualm4!
How are thing going? Did you found a solution?

**Comment by pascualm4** [comment]
Hi @Nayjest I have a question how to install the view-components/grids. I clone the repo on my project but I don't know what is the name of the class to put in the config/app.php file. In the nayjest/grids package it's very documented.

**Comment by pascualm4** [comment]
Hi @Nayjest I found a solution using the package view-components/grids. The DataProvider originally was an Elloquent/Collection. I transform that to an Array and works well. Only I have two issues but I will open another. Thanks for your help.
