### ISSUE TITLE
Daterangepicker add cancel method

### ISSUE THREAD

**Issue by wdog** [Nayjest/Grids#143]
hi @Nayjest  i've made a little modification to the datarange picker adding the 
possibility to reset the values. ( I hope it can be considered an enhancement)

even it is not in your intention to use this method maybe can be useful as an example fot those who wants to create their own views

#https://github.com/wdog/Grids/commit/d54702390b45439384ca6bd696b7d9cf5bc9d1eb

**Comment by Nayjest** [comment]
Hi!
Looks gool, please create pull-request, I will merge it.

**Comment by wdog** [comment]
done! It's my first pull request

**Comment by Nayjest** [comment]
My congratulations =)
I will examine it now.
