### ISSUE TITLE
Filter box

### ISSUE THREAD

**Issue by DevGentle** [Nayjest/Grids#151]
I have a question .

Is it possible to fixed width of a filter box in this picture

![screen shot 2559-08-13 at 7 08 55 pm](https://cloud.githubusercontent.com/assets/20085539/17643099/9ba3a8a4-6189-11e6-9ddb-dff0c58f547b.png)

**Comment by Nayjest** [comment]
Hi!
You can do it many ways, but I would recommend to use just CSS without modifying php code.

**Comment by DevGentle** [comment]
Ok
I'm really sorry to ask this question

Which file I should write CSS . Did you have some example ?

**Comment by Nayjest** [comment]
Write it to main .css file of your project :)
Or you can include it using `<style>` tag to layout of page where you use grid.

**Comment by DevGentle** [comment]
And about alias
   `
'HTML'  => 'Collective\Html\HtmlFacade',
`

I already add in my app config
`
'HTML' => Collective\Html\HtmlFacade::class,
`
But I can't use HTML in controller

```php
HTML:: .....
```

What i should do next plz help

**Comment by Nayjest** [comment]
Try `\HTML::`

**Comment by DevGentle** [comment]
Oh It's works !
Thank you very much Mr.Nayjest >.<

**Comment by Nayjest** [comment]
No problem :)
