### ISSUE TITLE
Show image in grid

### ISSUE THREAD

**Issue by DevGentle** [Nayjest/Grids#153]
Hi I have a question again.

The question is how to bring image to show on backend 

I've try to use setCallback but It's not work.

Did you have any solution for me. Plz help

Thank you.

**Comment by Nayjest** [comment]
Hi!
setCallback() is method that you need. Why isn't work? Any errors?

**Comment by DevGentle** [comment]
It's work now by using setCallback.

Thanks.

**Comment by Nayjest** [comment]
No problem
