### ISSUE TITLE
How to show data from backend to frontend

### ISSUE THREAD

**Issue by DevGentle** [Nayjest/Grids#157]
Hi I'm lerning in Laravel Doc and they said I must query in index function of each controller

But now my index function in my controller contains a grid nayjest so,

what is the solution to bring data from database to frontend please help i'm stuck at this section for 2 days. Please.

Oh and sorry for my bad in English >.<

Thank you.

**Comment by wdog** [comment]
It is not clear at all your question. explain better. 

In laravel you can do what you want, with Nayjest/Grids you can build the grid view in a method of the controller, then the controller returns grid view to the view. 

See the [Demo Code](https://github.com/Nayjest/grids-demo/blob/master/app/Http/Controllers/DemoController.php) and the [Demo](http://grids-demo.herokuapp.com/demo/example1)

**Comment by DevGentle** [comment]
Sorry about my English @wdog 

I have a question about how to bring data from database to my Webpage .

Because I'm already write grid nayjest config in my controller then I can't put my query code that I've learn from laravel doc 

so I want to know Is the other way to bring data from database to the webpage

**Comment by wdog** [comment]
immagine you have a `grid` and a collection of `books` taken from a DB

just 


```php
$cfg = (new GridConfig())......
$grid = new Grid($cfg);
$grid = $grid->render();

$books = Books:all(); // your data from DB

return view('demo.default', compact('grid', 'books')); // <-- the books are passed to the view
```

then in the view you can use as you want the `$books`

**Comment by DevGentle** [comment]
but I have 2 type of view "Frontend" and "Backend"

It's must show different data. That mean I must have 2 view return for "Frontend" and "Backend"
So what is the solution to do this Can you recommend me how to do this.

Thanks.

**Comment by wdog** [comment]
I think that the best solution is to use two controllers, or at least two method.

I suggest you to "touch" a little deeper laravel out of the box before using packages. 
This github  is related only to Grids and not to general problems related with laravel.

**Comment by DevGentle** [comment]
@wdog 
Ok thanks a lot for answer my question
