### ISSUE TITLE
Grid addFilter function

### ISSUE THREAD

**Issue by DevGentle** [Nayjest/Grids#161]
I have **Product model** that have **_FK_** relations from **ProductCategory model**

and when I filter product_category in products table It's not show anything.
 Can you tell me how to fix this ?

Thanks

This is my Controller filter code
```PHP
->addFilter(
   (new FilterConfig)
      ->setName('category_main_id')
      ->setOperator(FilterConfig::OPERATOR_LIKE)
)
```

**Comment by Nayjest** [comment]
Try to see what DB questies are produced by Grid to debug it.
See https://laravel.com/docs/4.2/database#query-logging

**Comment by Nayjest** [comment]
Without additional information I can't help, closing this issue.

**Comment by DevGentle** [comment]
Oh sorry @Nayjest It's works now Thank you.
