### ISSUE TITLE
The Form tag is being removed itself only in first row

### ISSUE THREAD

**Issue by ratbek** [Nayjest/Grids#162]
Hello!
I have added a column "Actions" which contains a Form tag with delete button in it. But somehow the Form tag is being removed itself only first row. In other rows it is ok, i.e. the Form tag is not being removed.
Why is this happening?

Code below:

(new FieldConfig)
                        ->setName('actions')
                        ->setLabel('Действия')
                        ->setCallback(function ($var, ObjectDataRow $row) {
                            $watchedProductModel = $row->getSrc();
                            $htmlButtons =  '<a class="btn btn-success" href="'.route('watched-product.show', $watchedProductModel->id).'"><i class="fa fa-eye" title="Показать"></i></a>'.
                                FormFacade::open(['class'=>'form_delete', 'method' => 'DELETE','route' => ['watched-product.destroy', $watchedProductModel->id],'style'=>'display:inline']).
                                '<button class="btn btn-danger delete" title="Удалить"><i class="fa fa-trash"></i></button>'.
                                FormFacade::close();
                            return $htmlButtons;
                        })
                    ,

**Comment by Nayjest** [comment]
Hi!
Grid is already placed into form, don't add new forms inside, use javascript to submit data to concrete controller action or submit outer form & process input in same controller action where grid is created.

**Comment by ratbek** [comment]
Thank you. I got it.
