### ISSUE TITLE
Allow pass through of get parameters - Smart input handling allows to avoid conflicts with get parameters 

### ISSUE THREAD

**Issue by osthafen** [Nayjest/Grids#164]
Hi Vitaliy,
I like your work very much!
I couldn't manage to easily use extra get parameters and have them included in the links of the filter, sorting and pagination.
I managed to copy and alter the views to add a custom get-parameter to sorting and filtering but still  the pagination needs extra work - I tried with (Laravel 5.3):
`$grid->getConfig()
            ->getDataProvider()
            ->getPaginator()
            ->appends(['extra_get_parameter' => $extra_get_parameter]);`
But this sets the query back to initial state.
Is there an easier way to accomplish this?
Thanks a lot!
Martin

**Comment by Nayjest** [comment]
Hi!
Pagination preserves input values inside `$_GET[<grid_name>]`,

 try to use parameters like `$_GET[<grid_name>][<some param>]`
