### ISSUE TITLE
Example to export as excel

### ISSUE THREAD

**Issue by bionimic** [Nayjest/Grids#165]
Hi Nayjest,

Can you give me example to do export as excel.

I just want the column name and each row. But all I get is html data (tags, weird characters and etc). please help me. thanks!

**Comment by wdog** [comment]
have you seen the demo file?

https://github.com/Nayjest/grids-demo/blob/master/app/Http/Controllers/DemoController.php

http://grids-demo.herokuapp.com/demo/example4

**Comment by Nayjest** [comment]
Thanks to @wdog for fast response.
Yep, just add `new ExcelExport()` to grid [example]( https://github.com/Nayjest/grids-demo/blob/master/app/Http/Controllers/DemoController.php#L193)
