### ISSUE TITLE
Avg And TotalsRow For All Data 

### ISSUE THREAD

**Issue by ehsanphp** [Nayjest/Grids#170]
how can I
 Get Avg And TotalsRow For All Data  Not the number of each page

**Comment by Nayjest** [comment]
See https://github.com/Nayjest/grids-demo/blob/master/app/Http/Controllers/DemoController.php#L210
```php
(new TotalsRow(['posts_count', 'comments_count']))
    ->setFieldOperations([
        'posts_count' => TotalsRow::OPERATION_AVG,
        'comments_count' => TotalsRow::OPERATION_AVG,
]),
```

**Comment by wdog** [comment]
@ehsanphp is asking (I suppose) for the total of **all rows**, not only the paged ones.

TotalRows.php is listening for `DataProvider::EVENT_FETCH_ROW` and performing operation.

I'm trying to figure how to get the query without the filters from the `DataProvider`

**Comment by ehsanphp** [comment]
Get Avg And TotalsRow For All Data

**Comment by Nayjest** [comment]
Oh, there is no such functionality out-of the box.
You need to precalculate it in controller and render inside grid using template overriding / creating custom component.

**Comment by wdog** [comment]
hey @ehsanphp  maybe i can give you a little hint
suppose you want to view the sum of the column `price`

```php
$dp = new EloquentDataProvider($records);

$collection =$dp->getBuilder()->getModels();
$tot = 0;
foreach ($collection as $element){
    $tot += $element->price;
}
// you can use $tot somewhere in the view or in the grid
// test it dump($tot);
//...
$grid = new Grid(
    (new GridConfig)->setDataProvider($dp)
   ...
);
```

In my case it works... I've not found a better solution at the moment
