### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by AnowarCST** [Nayjest/Grids#177]
There have a laravel error.

> No supported encrypter found. The cipher and / or key length are invalid.

link: [Demonstration Link](http://grids-demo.herokuapp.com/demo/example4)

**Comment by Nayjest** [comment]
Looks like laravel framework removed ext-mcrypt from its requirements

**Comment by Nayjest** [comment]
Fixed.
Strange Leravel issue.
This helped: https://github.com/Nayjest/grids-demo/commit/5196d29fe68d28179ba792ca1865a21adc4e6eba
