### ISSUE TITLE
<td> background-color getting color from the database

### ISSUE THREAD

**Issue by RafaelRodriguesFraga** [Nayjest/Grids#195]
Hey guys, can someone help me? How I can retrieve the color from the database with the color itself and not hexadecimal?

I have a grid that has a column named Color. I get these colors from the Database., but, like I said, it is in hexadecimal, not showing the color instead..

                Name   |   Color 
 Name  from the Database   |   #FFF

How can I display white instead #FFF? I tried with setCallback but when I try to call the variable I'm getting an error: Trying to get property of color of non-object.

**Comment by RafaelRodriguesFraga** [comment]
i'm getting another error that I coudn't not find anywhere. 

when I do ExcelExport, I get: Call to undefined method Maatwebsite\Excel\Excel::create()

**Comment by wdog** [comment]
after a quick test I found that this works

```php
( new FieldConfig )
   ->setName( 'color' )
   ->setLabel( 'color' )
   ->setCallback( function ( $v ) {
       return "<div style='background-color:$v;width:15px'>&nbsp;</div>";
    } ),
```

**Comment by wdog** [comment]
for `Maatwebsite`: have you added on `config/app.php` 

in providers

```php
Maatwebsite\Excel\ExcelServiceProvider::class,
```
in aliases

```php
'Excel'  => Maatwebsite\Excel\Facades\Excel::class,
```

**Comment by RafaelRodriguesFraga** [comment]
THANK YOU SO MUCH, IT WORKED.

Now, for the Excel, the method create is depreciated. I need to use another.
