### ISSUE TITLE
How me fix error "Class 'Input' not found"

### ISSUE THREAD

**Issue by Rsl561292** [Nayjest/Grids#200]
Hello. I installed this package and showing me error "Class 'Input' not found" in file D:\OSPanel\domains\laravelstudy.loc\vendor\nayjest\grids\src\GridInputProcessor.php. Please help me fix the error. Thanks.

**Comment by Nayjest** [comment]
Guys, are they removed Input class alias from Laravel by default?
If so, I think we need to replace alias usage to full quantified class name.
Sorry, I'm not watching Laravel changes last years.

If somebody wants to help with pull request, you are welcome.

**Comment by Nayjest** [comment]
Fixed in PR 217
https://github.com/Nayjest/Grids/pull/217
Thanks to @enoonan 
Released in v2.0.2
