### ISSUE TITLE
Class 'Input' not found

### ISSUE THREAD

**Issue by buibr** [Nayjest/Grids#208]
`Class 'Input' not found (View: /Work/Web/Files/orientdoors/_web3/resources/views/back/carousel/index.blade.php)
`

after looking to `/vendor/nayjest/grids/src/` folder, this class is not really found.

**Comment by Nayjest** [comment]
Hi!
- See laravelcollective/html package
- See Laravel facades / class aliases
This class should be available in Laravel app by default

**Comment by Nayjest** [comment]
See https://github.com/Nayjest/Grids/issues/200
