### ISSUE TITLE
Expected date format in the database

### ISSUE THREAD

**Issue by britisharmy** [Nayjest/Grids#212]
I am using mysql to store my dates and i want to have a date range picker.

What is the format of the date does the package accept so that i can store in a way that shall work well with the package.

From the code https://github.com/Nayjest/Grids/blob/master/src/Components/Filters/DateRangePicker.php

seems to be Y-m-d

Is this so?

**Comment by Nayjest** [comment]
Hi
Yep, Y-m-d always worked (1970-01-01)
