### ISSUE TITLE
CsvExport Component doesn't work correctly

### ISSUE THREAD

**Issue by alexonline82** [Nayjest/Grids#33]
if i use csv export component, the start from the document included in csv file.

    $grid = new Grid(
            (new GridConfig)
       ..... some fields ....
    ->setComponents([

                (new THead)

                ,
                (new TFoot)
                    ->addComponent(
                        (new CsvExport)
                     )
         ])

Export starts with 

    <section class="main-content">
    <div class="container-fluid">
        
            <div class="panel panel-default">
                <div class="panel-heading lead">Grid-Header</div>
                <div class="panel-body">
                    					<div class="table-responsive">

**Comment by Nayjest** [comment]
Ok, give me few minutes, I will try to reproduce bug

**Comment by Nayjest** [comment]
Can't reproduce.
Looks like you start output before rendering grid.
1. Construct grid before any output (in controller for example, do not construct grid in view).
2. To be sure, render grid before passing it to view:
```php
$grid = ... // constructing grid here
$grid = $grid->render(); // add this line
...
return View::make('you-view', ['grid' => $grid, ...]) // then pass grid to view
```

**Comment by alexonline82** [comment]
ok, thats the problem. i render the grid in the view. 

btw. copied you csv-component and build an excel component base on https://github.com/Maatwebsite/Laravel-Excel/tree/v2.0.2 locally. is it interesting for you? i don't very familiar with pull requests at the moment.

**Comment by Nayjest** [comment]
Sure interesting! If you are not familiar with github pull requests, you can just paste code to https://gist.github.com , send me a link and I will review it and include in my package with your credits if it's good.  
But anyway, I recommend you to learn learn how to use pull requests, it's quite easy.

**Comment by alexonline82** [comment]
Yes, thats the plan. I do it tomorrow ;-)

**Comment by alexonline82** [comment]
Sorry, today ;-) I created a pull request.
