### ISSUE TITLE
Add documentation for DateRangePicker

### ISSUE THREAD

**Issue by TUNER88** [Nayjest/Grids#36]
How can i use DateRangePicker?
Is there any documentation?

**Comment by Nayjest** [comment]
Documentation for components isn't ready yet.
You can help, making pull requests to https://github.com/Nayjest/Grids.wiki.git

I will provide usage example for you at [demo application](http://grids-demo.herokuapp.com/demo/example4) in 1-2 hours

**Comment by Nayjest** [comment]
Done.
(demo)[https://grids-demo.herokuapp.com/demo/example4]
(code)[https://github.com/Nayjest/grids-demo/blob/master/app/Http/Controllers/DemoController.php#L164]

Now working on documentation page

**Comment by Nayjest** [comment]
Done, see [DateRangePicker documentation](https://github.com/Nayjest/Grids/wiki/Components-Documentation#nayjestgridscomponentsfiltersdaterangepicker)

**Comment by Nayjest** [comment]
Please give me know if it helped.

**Comment by Nayjest** [comment]
Sorry, there was broken link to demo, it doesn't works correctly over https, only http:
[demo](http://grids-demo.herokuapp.com/demo/example4)

**Comment by TUNER88** [comment]
@Nayjest seems to working, thx
