### ISSUE TITLE
Apply select filter immediately 

### ISSUE THREAD

**Issue by TUNER88** [Nayjest/Grids#37]
Submit filter data on select change.
This would be really nice usability improvement.
Thx

**Comment by Nayjest** [comment]
Ok, good feature, I'm planning to implement this.
See tomorrow or monday releases.

**Comment by TUNER88** [comment]
@Nayjest thx

**Comment by Nayjest** [comment]
use  SelectFilterConfig::setSubmittedOnChange(bool)

**Comment by TUNER88** [comment]
@Nayjest awesome, thx :+1:

**Comment by Nayjest** [comment]
* Bug found

**Comment by Nayjest** [comment]
Fixed in v0.7.13
