### ISSUE TITLE
Button for adjusting column gets hidden on change

### ISSUE THREAD

**Issue by gokigoks** [Nayjest/Grids#38]
When I change the shown columns the button gets hidden behind the drop down check box.
How can I fix this on the mean time?

**Comment by Nayjest** [comment]
Mmm it's hard to understand where is problem. Can you provide more details (code snippets, screenshots)?

Also, see example with usage of ColumnsHider component: http://grids-demo.herokuapp.com/demo/example4
Code: https://github.com/Nayjest/grids-demo/blob/master/app/Http/Controllers/DemoController.php

**Comment by gokigoks** [comment]
Hey, Actually, the issue was with the demo, nothing php related. you can replicate it with hiding all columns then checking the show all again. This will hide the column button behind its drop-down. 

btw, was the dynamic functionalities only with your demo?

**Comment by Nayjest** [comment]
Yep, thanx, I see the bug now.

```
btw, was the dynamic functionalities only with your demo?
```
Sorry, I don't understand the question.
What do you call 'dynamic functionalities'?

Demo includes some components bundled with nayjest/grids package, but not all of them.
All functionalities implemented within components. 
The only thing that you need to include to your app manually -- JS libraries required for some components like jQuery, bootstrap, etc. and css.
Also, by default, if you don't add specific components like JS date pickers, rendered grid will not contain any JS.

Well, in any case, clarify your question if you want to get correct answer :)

**Comment by Nayjest** [comment]
Regarding the bug, I will fix that in next release (beginning of the next week or earlier).
Probably hiding & showing popup again when inputs changed will help. Also, I will research about possibility to close the popup on clicks outside it.

Mentioned popup is rendered using
Twitter Bootstrap Popover: http://getbootstrap.com/javascript/#popovers
If you want to fix it on your own and can do it faster, pull requests are welcome!

**Comment by Nayjest** [comment]
Fixed in #d285e14acb338aad001ae7aff572f60389d02e97
Thanx to @gokigoks 
Now popover can be closed by clicking on any area outside.
