### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by cristi-ca** [Nayjest/Grids#39]
A full tutorial (or documentation) for a crud using Grids would be wonderful for a beginner.

**Comment by Nayjest** [comment]
You mean CRUD operations for rows within one grid reflected to DB?

**Comment by cristi-ca** [comment]
Yes. Your grid with such functionality (CRUD) would be very, very useful (something like grocery crud for codeigniter).
I have tried lots of Laravel grids/dasboards/admin , I think yours is the best  and most promising.
Please consider a tutorial, I can assure you that will be very much appreciated by a lot of Laravel newbies.
Thank you for your fast answer!

**Comment by Nayjest** [comment]
I will work on tutorial after next major release becouse I'm planning to make some important API changes (#43)
