### ISSUE TITLE
Customizing blades

### ISSUE THREAD

**Issue by TUNER88** [Nayjest/Grids#40]
How can i customise blades?

I have tried to update published blades from `app/resources/views/nayjest/grids/default/*`, but still get output from vendor directory (`app/vendor/nayjest/grids/resources/views`)

**Comment by Nayjest** [comment]
1. Which version of Laravel  was used?
2. Provide please full name of template you tried to customize (value passed to Component::setTemplate()) and path to corresponding file

**Comment by TUNER88** [comment]
@Nayjest thanks, We use Laravel 5. `Component::setTemplate()` works like charm, thx!
