### ISSUE TITLE
DBAL example

### ISSUE THREAD

**Issue by dan-root** [Nayjest/Grids#44]
Can you pls post an example of grid with DBAL source?
Tried but got an error on laravel 5. thanks
FatalErrorException in DbalDataProvider.php line 72: Call to undefined method Illuminate\Pagination\Paginator::make()

**Comment by Nayjest** [comment]
Hi!
Thanks for the report.
DbalDataProvider was tested only with Laravel 4 and pagination was changed in Laravel 5, so looks like there is bug in DbalDataProvider::getPaginator()

**Comment by Nayjest** [comment]
If you want, you can help to provide implementation of DbalDataProvider::getPaginator() that works for Laravel 5, I will appreciate it.

Also, If you use Laravel 5, use Nayjest\Grids\Components\Laravel5\Pager instead of Nayjest\Grids\Components\Pager for rendering pagination.

**Comment by Nayjest** [comment]
Regarding example, fast one:

1. Create DBAL query builder:
```php
$query = \DB::connection()->connection()->getDoctrineConnection()->createQueryBuilder();
/// instance of \Doctrine\DBAL\Query\QueryBuilder
```
2. Write your query
```php
$query->select(
                'user_id',
                'SUM(salary) as total_salary'
            )
            ->from('salary')
            ->groupBy('user_id');
```
3. Create your grid, see examples in documentation.
If you construct grid from array using Grids::make, just pass $query to 'src' field:
```php
Grids:make([
    'src' => $query,
    'columns' => ...
    ....
])
```
Otherwise, instantiate DbalDataProvider manually with $query as constructor argument, pass it to $gridCondif->setDataProvider($provider) and so on.

**Comment by Nayjest** [comment]
Working on example now

**Comment by Nayjest** [comment]
```
FatalErrorException in DbalDataProvider.php line 72:
Call to undefined method Illuminate\Pagination\Paginator::make()
```
Fixed in release 0.8.1

**Comment by Nayjest** [comment]
@dan-root Please, update nayjest/grids in your project to version 0.8.1

Example of grids with DbalDataProvider available here:

* [Demo](http://grids-demo.herokuapp.com/demo/example5)
* [Code](https://github.com/Nayjest/grids-demo/blob/master/app/Http/Controllers/DemoController.php#L230)

Give me know whether it works fine now.

**Comment by Nayjest** [comment]
You also can use https://github.com/Nayjest/Laravel_DoctrineDBAL to see DB queries performed via Doctrine DBAL in debug bar (barryvdh/laravel-debugbar package)

**Comment by dan-root** [comment]
hey,
thank you! it looks good now. i really appreciate your fast answer!
i m new to laravel(started learning 2weeks ago) and i m trying to find some
nice widgets like grids to build an admin interface.

question what are advantages of using doctrine DBAL vs laravel built in
query build? http://laravel.com/docs/5.0/queries

On Thu, Apr 23, 2015 at 7:04 PM, Vitaliy Stepanenko <
notifications@github.com> wrote:

> @dan-root <https://github.com/dan-root> Please, update nayjest/grids in
> your project to version 0.8.1
>
> Example of grids with DbalDataProvider available here:
>
>    - Demo <http://grids-demo.herokuapp.com/demo/example5>
>    - Code
>    <https://github.com/Nayjest/grids-demo/blob/master/app/Http/Controllers/DemoController.php#L230>
>
> Give me know whether it works fine now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Nayjest/Grids/issues/44#issuecomment-95634601>.
>

-- 
*IMPORTANT:* This email and any files included with it may contain 
privileged, proprietary and/or confidential information that is for the 
sole use of the intended recipient(s). Any disclosure, copying, 
distribution, posting, or use of the information contained in or attached 
to this email is prohibited unless permitted by the sender. If you have 
received this email in error, please immediately notify the sender via 
return email, telephone, or fax and destroy this original transmission and 
its included files without reading or saving it in any manner. Thank you.

**Comment by Nayjest** [comment]
@dan-root, DBAL is more flexible, it's better if you need very complex queries. 
In other cases, if you use Laravel, Eloquent queries are preferreble.

**Comment by wdog** [comment]
hi

sorry for re-open but i cannot use `SelectFilterConfig` with DBAL

I'm still getting 

```
Method Nayjest\Grids\Grid::__toString() must not throw an exception
```


here the code i'm using


```
  (new FieldConfig)
          ->setName('stato_descrizione')
          ->setLabel('Stato')
          ->addFilter(
            (new SelectFilterConfig())
              ->setName('stato_id')
              ->setOptions($arrStati)
              ->setOperator(FilterConfig::OPERATOR_EQ)
              ->setSubmittedOnChange(true)
          )
```
the original query was something like (but with many joins)

```sql
select a.name, a.stato_id, a.stato_descrizione from objects a
```

any suggestion?

**Comment by wdog** [comment]
ops
i'm missed the 

```php
    $grid = $grid->render();
```

now works
sorry
