### ISSUE TITLE
Redirect to valid page number if requested page has no items.

### ISSUE THREAD

**Issue by TUNER88** [Nayjest/Grids#47]
E.g `user 1` is on page 4 of 5 available.
`user 2` delete all items on page 4 and 5.
`user 1` try to navigate to page 5 and get empty page.

It would be better if user were redirected to last available page.

My workaround is using laravel pagination before initialize grid.
Is there any better way to solve this problem?

``` php
$contracts = Contract::paginate(10);
$currPage = \Illuminate\Support\Facades\Request::get('contract')['page'];

if ((int)$currPage > $contracts->lastPage()){
    $url = action('ContractController@index', ['contract' => ['page' => $contracts->lastPage()]]);
    return redirect($url);
}

$grid = new Grid(
    (new GridConfig)
    ...
```

**Comment by Nayjest** [comment]
Hi again!
Thanks for report.

You can implement grid component that will perform redirect if current_page  > last_page.
One cons.: it's not convenient ro return Redirect response from grid to controller, so you will need to print response inside your component and stop application using exit() (it's not a good practice).

See \Nayjest\Grids\Components\ShowingRecords, there is example how to get pagination data and save compatibility with both Laravel 4 and Laravel 5.

If you will work on such component, please, share it, I will make code review and include it to Grids :)

**Comment by Nayjest** [comment]
Alternative solution: Component can show popoup saying that grid contains less records now, there is no page #X  and offering to redirect to last available page.
