### ISSUE TITLE
Add html attributes to <tr> in grid

### ISSUE THREAD

**Issue by damienIN** [Nayjest/Grids#48]
How would I go about adding onclicks/ids/classes to each row of the grid if I wanted each row to be a unique link?

**Comment by Nayjest** [comment]
Hi!
**If you want to add same attributes to each row:**
``` php
$gridConfig->getRowComponent()->setAttributes([
     'class' => 'table-row'
]);
```

**If you wand to add attributes based on data from current row:**

1. Create your own class for table row tag, that will add required attributes:

```php
<?php
namespace My\App;
use Nayjest\Grids\Components\Tr;
class MyTr extends Tr
{
    public function getAttributes()
    {
        // Get value of 'user_id' column from current row
        $userId = $this->getDataRow()->getCellValue('user_id');
        // Prepare your attributes
        $newAttributes = [
             'data-link' => route('users.profile', [$userId]),
             'class' => 'my-class table-row'
        ];
        return array_merge(parent::getAttributes(), $newAttributes);
    }
}
```

2. Use that class in grid configuration

```php
$gridConfig->setRowComponent(new MyTr());
```

**Comment by Nayjest** [comment]
Please let me know whether it helped.

**Comment by damienIN** [comment]
That's pefect. Thanks for the help!

**Comment by damienIN** [comment]
I am able to successfully call the function on GridConfig, but nothing appears to happen. Here's my call...

 public static function makeGrid($query){
        $grid = new Grid(
            (new GridConfig)
                ->setDataProvider(
                    new EloquentDataProvider($query)
                )
                ->setName('example_grid4')
                ->setPageSize(15)
                ->setColumns([
                    (new FieldConfig)
                        ->setName('id')
                        ->setLabel('ID')
                        ->setSortable(true)
                        ->setSorting(Grid::SORT_ASC)
                    ,
                    (new FieldConfig)
                        ->setName('created_at')
                        ->setLabel('Invoice Date')
                        ->setSortable(true)
                    ,
                    (new FieldConfig)
                        ->setName('first_name')
                        ->setLabel('First Name')
                        ->setSortable(true)
                        ->setSorting(Grid::SORT_ASC)
                        ->addFilter(
                            (new FilterConfig)
                                ->setOperator(FilterConfig::OPERATOR_LIKE)
                        )
                    ,
                    (new FieldConfig)
                        ->setName('last_name')
                        ->setLabel('Last Name')
                        ->setSortable(true)
                        ->setSorting(Grid::SORT_ASC)
                        ->addFilter(
                            (new FilterConfig)
                                ->setOperator(FilterConfig::OPERATOR_LIKE)
                        )
                    ,
                    (new FieldConfig)
                        ->setName('total')
                        ->setLabel('Total')
                        ->setSortable(true)
                        ->setSorting(Grid::SORT_ASC)
                        ->setCallback(function ($val) {
                            return '$' . money_format('%(#10n', $val);
                        })
                        ->addFilter(
                            (new FilterConfig)
                                ->setOperator(FilterConfig::OPERATOR_GTE)
                        )
                        ->addFilter(
                            (new FilterConfig)
                                ->setOperator(FilterConfig::OPERATOR_LSE)
                        )
                    ,
                ])
                ->setComponents([
                    (new THead)
                        ->setComponents([
                            (new ColumnHeadersRow),
                            (new FiltersRow)->addComponents([
                                (new RenderFunc(function () {
                                    return HTML::style('js/daterangepicker/daterangepicker-bs3.css')
                                    . HTML::script('js/moment/moment-with-locales.js')
                                    . HTML::script('js/daterangepicker/daterangepicker.js')
                                    . "<style>
                                                .daterangepicker td.available.active,
                                                .daterangepicker li.active,
                                                .daterangepicker li:hover {
                                                    color:black !important;
                                                    font-weight: bold;
                                                }
                                           </style>";
                                }))
                                    ->setRenderSection('filters_row_column_created_at'),
                                (new DateRangePicker)
                                    ->setName('created_at')
                                    ->setRenderSection('filters_row_column_created_at')
                                    ->setDefaultValue([date('Y-m-d'), (new Carbon('tomorrow'))->toDateString() ])
                            ])
                            ,
                            (new OneCellRow)
                                ->setRenderSection(RenderableRegistry::SECTION_END)
                                ->setComponents([
                                    new RecordsPerPage,
                                    new ColumnsHider,
                                    (new CsvExport)
                                        ->setFileName('invoice_report' . date('Y-m-d'))
                                    ,
                                    (new HtmlTag)
                                        ->setContent('<span class="glyphicon glyphicon-refresh"></span> Filter')
                                        ->setTagName('button')
                                        ->setRenderSection(RenderableRegistry::SECTION_END)
                                        ->setAttributes([
                                            'class' => 'btn btn-success btn-sm'
                                        ])
                                ])
                        ])
                    ,
                ])
                ->setRowComponent(new DmwTr())


        );
        $grid = $grid->render();
        return $grid;
    }

**Comment by damienIN** [comment]
I took a litte bit of a further look and it appears that it is adding a single row as html at the top ofhe form like....

    <mytr myattribute="value"></mytr>

**Comment by Nayjest** [comment]
Override getTagName method or call your class Tr:
```php
<?php
namespace My\App;
use Nayjest\Grids\Components\Tr;
class MyTr extends Tr
{
    ...
    public function getTagName() { return 'tr'; }
    ...
}
```

**Comment by damienIN** [comment]
Got it. Now working as expected.

Thanks!
