### ISSUE TITLE
Filtering with SetCallback

### ISSUE THREAD

**Issue by lsaintmaxent** [Nayjest/Grids#50]
Hey Man,
i've some troubles filtering a column of the grid with my data, and i was wondering if you could help me or tell me that what i'm doing is wrong :)

So my dataset is a join between client and invoices.

On a column of my grid i display the client who own the invoice. So in the setCallBack method i use the client_id in the invoice to retreive is name :
 ->setCallback(function ($val) {	
$client_intitule = DB::select("SELECT clients_raison_sociale FROM tri_clients WHERE clients_id = ?",array($val));
	foreach($client_intitule as $ci){
		$clients_raison_sociale = $ci->clients_raison_sociale;
	}
	return $clients_raison_sociale;
})
This is working fine :)
But now i want to add a filter on the name of the client but i have only the id of the client in my dataset so i can only filter on his id.

I read somewhere about the "setFilteringFunc" and i tried something like:
->setFilteringFunc(function($val, EloquentDataProvider $provider) {
		$builder = $provider->getBuilder();
		echo $val;
                $builder->where('tri_clients.clients_raison_sociale', 'like', "$val");
  })

But i can't get it working, but the $val in filteringFunc is the filter input of the user.
Do you have any idea what i'm doing wrong ?

**Comment by Nayjest** [comment]
Hi!
You load client data in separate query, so it's impossible to filter by client name this way.
You need to join tri_clients table in your main query and then it will be possible to filter it.

**Comment by Nayjest** [comment]
Also, performing querties in column callback (additional queries for each row) is inefficiently in terms of performance, so in any case, sql join will work better.

**Comment by lsaintmaxent** [comment]
Thx a lot man, i'm gonna fix it now.

Have a nice day :)

**Comment by lsaintmaxent** [comment]
I'm trying to fix this right now and i'm getting two issues : 

- Fristable, I don't know how to attach two different colum of my model to the FieldConfig (to get the same render as my query right now).

- And when i define the filter function, if u link two colum on an id (for example client_id) and you overwrite the two filterFunc, it's seem that the both filter input share the same value.

Did you ever encounter something like this ?

It's probably because i don't give the right information to the column.

Could you help me one more time (sorry man, i know that you can't help all people on all project) but i would really appreciate that.

**Comment by Nayjest** [comment]
>> Fristable, I don't know how to attach two different colum of my model to the FieldConfig to get the same render as my query right now.
FieldConfig.name is responsible only for default behavior (if no callback specified) and first argument passed to calback (value with same name extracted from DataRow), in second argument you get DataRow instance and can get any values from it.

>> And when i define the filter function, if u link two colum on an id (for example client_id) and you overwrite the two filterFunc, it's seem that the both filter input share the same value.
You can specify different names for filters (by default it's column name and html input will be created with same name)

**Comment by lsaintmaxent** [comment]
Thanks a lot man,
awesome job and awesome support.

Have a nice day :)
