### ISSUE TITLE
Bulk actions

### ISSUE THREAD

**Issue by pedrambehroozi** [Nayjest/Grids#51]
Is it possible to implement bulk actions? I want to delete multiple rows. I need checkboxes in front of every row and delete selected rows. How could I implement this?

Thanks.

**Comment by Nayjest** [comment]
Hi!
Just create column and specify callback (FieldConfig::setCallback()) that will render checkboxes, second argument will contain DataRow object, so you can get something like rowID from DataProvider

**Comment by pedrambehroozi** [comment]
Hi, thanks for reply.
Yes, I rendered checkboxes, so how can I submit the form and where should I handle the request?

**Comment by Nayjest** [comment]
You can handle request in controller before rendering grid.
Or you can create grid component that will handle request (see base classes in Components/Base) to makr it reusable.
See CsvExport component for example, it renders button and handles request to return CSV data instead of html grid if there is 'csv' get param.

**Comment by Nayjest** [comment]
Note, that by default grid form will be submitted to same action that renders it.

**Comment by jpldev** [comment]
How can I handle the request before rendering? 

I want to take the list of checkbox and pass through the list to a method (so I can change the state of the id-s selected)

$gridAlarm = new Grid(
             (new GridConfig)
                 ->setName('reporte-alarms')
                 ->setDataProvider(new EloquentDataProvider($query))
                 ->setCachingTime(5) 
                 ->setColumns([                
                     (new FieldConfig)
                     ->setName('checkboxUps')
                     ->setLabel('Seleccionar')
                     ->setCallback(function ($val, $row){
                         $checkbox= "<input type='checkbox' name='alarmsSelected[]' value='$val' id='$val' />";
                         return $checkbox;

                     })

I want to handle the request and pass alarmsSelected (my array of checkbox)

How can I do this?

I will apreciate an example.

Thanks for this extension! It has a lot of functionalities
