### ISSUE TITLE
Update to use laravelcollective/html

### ISSUE THREAD

**Issue by mstephens** [Nayjest/Grids#52]
FYI, "illuminate/html" should be replaced with "laravelcollective/html" as the former is no longer supported and the latter contains additional methods too (such as a numeric field etc.)

    "require": {
        "nayjest/grids": "~0.8",
        "illuminate/html": "~5"
    },

    "require": {
        "nayjest/grids": "~0.8",
        "laravelcollective/html": "~5.0"
    },

More information can be found [here...](http://laravelcollective.com/docs/5.0/html)

**Comment by Nayjest** [comment]
Hi! Thanks, I will fix it.

**Comment by Nayjest** [comment]
Done, use grids v0.9
