### ISSUE TITLE
How to create grid from a array, a StdClass object like a json_decode, or a RESTful API?

### ISSUE THREAD

**Issue by Maykonn** [Nayjest/Grids#54]
My app is a client app, not make use from Eloquent or Droctrine, query, etc. My data source is my  external API. So, how to populate a grid from a stdclass object? My API return json string so I get a StdClass object with json_decode.

**Comment by Nayjest** [comment]
Hi!
Currently you can't, this feature is still in development (See https://github.com/Nayjest/ViewComponents/blob/master/tests/webapp/Controller.php , view-components will be a core package for next major Grids release).

**Comment by Maykonn** [comment]
Thanks @Nayjest !
