### ISSUE TITLE
SelectFilter

### ISSUE THREAD

**Issue by majacirkova1989** [Nayjest/Grids#55]
Hi , is there option in SelectFilter for ading id on each select filter ????

I have this:
(new SelectFilter)
                                        ->setDefaultValue('g_name')
                                        ->setName('Group Name')
                                        ->setVariants([$group_name])
                                        ->setFilteringFunc(
                                            (function($val, EloquentDataProvider $dp) {
                                                /** @var Illuminate\Database\Eloquent\Builder $builder */
                                                $builder = $dp->getBuilder();
                                                $builder->where('group.id', 'like', $val);
                                                //dd($builder);
                                            })
                                        )

But i also i have more so i want to identify each of them to be different ???

**Comment by Nayjest** [comment]
Hi!
You can override component template and render there select with id. 
See setTemplate($tpl) method.

**Comment by majacirkova1989** [comment]
Okey , but what is this $tpl string or ??
