### ISSUE TITLE
Access on checkbox from inside of the grid ??

### ISSUE THREAD

**Issue by majacirkova1989** [Nayjest/Grids#56]
Hey ,

Is it possible on multiple select of checkboxes and one button on submit to render(filter) data in grid ? And how to do that ??
Really appreciate some help.

Have a nice day,
Maja.

**Comment by Nayjest** [comment]
@lsaintmaxent described how to render checkboxes here https://github.com/Nayjest/Grids/issues/53#issuecomment-115677549

Grid already have a form, so all your checkboxes will be submitted.

You can create submit button this way: 
```php
$someComponent->addComponent(new RenderFunc(function(){
    return "<button type ='submit'>Submit</button> ";
}));
```
Then just process input in controller.
If you use EloquentDataProvider, you can create query builder, add instructions for filtering and then pass it to data provider.

**Comment by majacirkova1989** [comment]
Okey thanks i solve it :)

**Comment by jpldev** [comment]
Please I need an example of how to render a list of checkbox and **how** to take the Ids submitted

**Comment by wdog** [comment]
a simple way is to use a callback

```php
(new FieldConfig)
    ->setName('id')
    ->setLabel('select')
    ->setCallback(function ($val, ObjectDataRow $dr) {
         $data = $dr->getSrc();
         return "<input type='checkbox' class='scads' name='scad[]' value='$val' id='scad_$val' />";
    }),

```

**Comment by jpldev** [comment]
Thanks @wdog !!!


I could render the checkbox, now.. how and where can I take the Selected items?

I wanna handle the items with two buttons, added like this:


```
                                     (new HtmlTag)
                                     ->setContent('<span class="glyphicon glyphicon-ok">Clear</span>')
                                     ->setTagName('button')
                                     ->setAttributes([
                                         'type' => 'submit',
                                         'id'   => 'clr',
                                         'class' => 'btn btn-info btn-primary btn-sm'
                                     ]),
                                     (new HtmlTag)
                                     ->setContent('<span class="glyphicon glyphicon-saved">Ack</span>')
                                     ->setTagName('button')
                                     ->setAttributes([
                                        'type' => 'submit',
                                        'id'   => 'ack',
                                        'class' => 'btn btn-info btn-primary btn-sm'
                                     ])
```

**Comment by wdog** [comment]
you can do it with javascript looping all the items with class='my_checkbox_class' .

```php
$('#clr').on('click', function (e){
 e.preventDefaults();
  $('.scads').each ( function (idx,el){ 
     // do something
      console.log(el);
   });
}
```

**Comment by jpldev** [comment]
Thanks @wdog , I could do that, now, I was thinking, the goal of this is to change the state of the selected items...

I imagine to pass the ids  (to a route , the action of the form grid) and then in the controller change the state in the DB of each item. Instead of that can I do that from Javascript/jQuery like your example?
