### ISSUE TITLE
Templates for select filters

### ISSUE THREAD

**Issue by majacirkova1989** [Nayjest/Grids#59]
Hey can you explain to me how it works different templates for different select filters ???? 

Thanks a lot :)

**Comment by Nayjest** [comment]
Actually I can answer but I'm not sure that it will help you... 
Take different select filters(instances of \Nayjest\Grids\SelectFilterConfig), set different blade or php templates using setTemplate($tplName) method (you can take  vendor\nayjest\grids\resources\views\default\filters\select.php as example when you will create your custom templates), then render grid, see different selects --> became happy :3

Ask something more concrete please (if it's still actual)

**Comment by majacirkova1989** [comment]
Yeah i put two more templates in vendor\nayjest\grids\resources\views\default\filters\ like select.php i called them: checkboxselect.php and checkboxcompany.php . Here is the image from grid where are templates for filters:
http://i.imgur.com/WZiJnpt.png?1

As you can see i instantiate different templates for different columns with different component
in ColumnHeader but it gets only template from the first one :/


Here is code in ColumnHeader:
<?php
namespace Nayjest\Grids\Components;

use Nayjest\Grids\FieldConfig;
use Nayjest\Grids;

/**
 * Class ColumnHeader
 *
 * The component for rendering column header
 *
 * @package Nayjest\Grids\Components
 */


class ColumnHeader extends TableCell
{
    protected $tag_name = 'th';

    /**
     * @param FieldConfig $column
     * @return $this
     */
    public function setColumn(FieldConfig $column)
    {

        $this->setContent($column->getLabel());
        if ($column->isSortable()) {
            $this->addComponent(new SortingControl($column));
        }

        if($column->getLabel() == 'Select all') {
            $this->addComponent( (new HtmlTag)
                ->setContent('<input id="selectAll" type="checkbox"/>')
            );
        }

        if($column->getName()=='group') {
            $this->addComponent((new CheckBoxFilter));
        }

        else if($column->getName() == 'company') {
            $this->addComponent((new CheckBoxCompany));

        }
        return parent::setColumn($column);
    }
}

I want in different columns to show different templates, in my case there are 2 columns : 'group' and 'company' and i want to shows in each column different template , but only show template for group.

**Comment by Nayjest** [comment]
First of all, don't put any files to your vendors folder becouse it can be lost when you will run composer install/update.

In code example I can't see, how you assigning templates, but if CheckBoxFilter must be always used with one template and CheckBoxCompany with another, you can just override protected $template property for each of them.

**Comment by majacirkova1989** [comment]
But how to override protected $template  property  , can you show me an example , I don't know how to use it ????

**Comment by Nayjest** [comment]
```php
<?php

namespace Majacirkova\SuperApp\GridComponents;

use Nayjest\Grids\Components\Base\RenderableComponent;

class CheckBoxCompany extends RenderableComponent
{
    // will use my-grid-components/checkbox-company.blade.php from your app views folder
    protected $template = 'my-grid-components.checkbox-company';

   // some other code here if you need
}
```

**Comment by majacirkova1989** [comment]
Ok thanks i solve it :)
