### ISSUE TITLE
Cannot get paging to work

### ISSUE THREAD

**Issue by DigiDaz** [Nayjest/Grids#60]
Hi,

I am trying to get paging to work. I'm very new to Laravel so I may be missing something really obvious.

I have managed to get the pages like 1,2,3,4 etc but when I click on them nothing happens. There are links very similar to the examples but I cannot work out what should be happening when I click.

Here is the code for one of the links: http://192.168.1.211/manage/?manage%5Bpage%5D=2

Thanks in advance for any help

**Comment by Nayjest** [comment]
Hi!
I can't access http://192.168.1.211/manage/?manage%5Bpage%5D=2 to check what's wrong.

**Comment by Nayjest** [comment]
Looks like 192.168.1.211 is your internal IP not accessible from web.

**Comment by DigiDaz** [comment]
Thanks for the reply but yes, sorry, this is not currently out on the internet, just a local ip.

**Comment by Nayjest** [comment]
So, you use pagination component **from Grids package** for corresponding version of Laravel (there is L4 and L5 implementation), links are rendered but not clickable?

**Comment by DigiDaz** [comment]
Thank you for the answer, this issue is actually resolved now. I haven't yet nailed the problem but I was using, nginx on FreeBSD I have moved it to Ubuntu with Apache and all is well so I'm thinking now it may have been a rewrite issue.
