### ISSUE TITLE
filter on having

### ISSUE THREAD

**Issue by wdog** [Nayjest/Grids#61]
hello!

I'm trying to build a grid of collection of comics with "collection name" and the count(*) of
comics related. (  Collection  and Comic model with a one to many relation)

I'm a newbie with Laravel and more with your beautiful grid , please try to understand

I have used this EloquentDataProvider

```php
   $query = Collection::leftJoin('comics', 'comics.collection_id', '=', 'collections.id')
            ->select(DB::raw('collections.id as id ,collections.name as name ,count(*) as comics_count'))
            ->groupBy('collections.id', 'collections.name');
```

**question 1**
how can I filter **id** without using a setFilteringFunc? (using simple filter gives me error )

this works, but I'm not sure if it's the right way (or the only)

```php
    (new FieldConfig)
                    ->setName('id')
                    ->setLabel('ID')
                    ->setSortable(true)
                    ->setSorting(Grid::SORT_DESC)
                    ->addFilter(
                        (new FilterConfig)
                            ->setOperator(FilterConfig::OPERATOR_EQ)
                            ->setFilteringFunc(function ($val, EloquentDataProvider $provider) {
                                $provider->getBuilder()->where('collections.id', '=', $val);
                            })
                    ),
```
**question 2**
haw can I filter on count(*) (comics_count ) ? 

I beg you to write more examples or a guide/tutorial because the source code is too hard to understand for me

**Comment by Nayjest** [comment]
**Q1:**
You are doing all right, without filteringFunc probably it will throw error becouse filter generates "where id = :val" SQL and looks like it will be ambigous for your query (column aliases in mysql doesn't works for "where" section, therefore you can't do something like 'select a as b where b = 1'). 

If you don't like usage of setFilteringFunc, you can try to set custom name to filter like this:
```php
$filter->setName('collections.id');
```
instead of using setFilteringFunc, but **I'm not sure that it will work**

**Q2:**
Try something like
```php
$filter->setFilteringFunc(function ($val, EloquentDataProvider $provider) {
     $val = (int)$val;
     $provider->getBuilder()->whereRaw("count(comics.id) >= $val");
});

```

**Comment by wdog** [comment]
**Q1**

**it woks** :dart: 

```php
$filter->setName('collections.id');
```
**Q2**

**it woks** :dart: 
```php
$filter->setFilteringFunc(function ($val, EloquentDataProvider $provider) {
    $provider->getBuilder()->havingRaw(
        'count(comics.id) >= ?',
        [(int)$val] 
    );
});
```

thanks a lot for your time :+1:
