### ISSUE TITLE
Using forms inside of a column

### ISSUE THREAD

**Issue by asaf050** [Nayjest/Grids#63]
Hey,
I want to use a form (for example - deletion form) inside of a column.
There is a problem that the whole table wrapped by a form so it won't work...
What we can do about it?

Thanks

**Comment by asaf050** [comment]
Right now I'm using an ugly hack
  new RenderFunc( function() {
                                            return '</form>';
                                        } ) ,

**Comment by Nayjest** [comment]
Hi!
Without whole table wrapped by a form alot of features will not work, so I recommend you to use main form or send your requests via ajax or use hidden form before/after grid that will be submitted via js.
