### ISSUE TITLE
ExcelExport Component

### ISSUE THREAD

**Issue by majacirkova1989** [Nayjest/Grids#64]
Hey, all i want to do is to change ExcelExport component default to get me export without first column which is Select all and the last column Edit all. How to change that without to unchecked in ColumnHider.

**Comment by Nayjest** [comment]
```php
ExcelExport::setIgnoredColumns([$columnName1, $columnName2])
```

**Comment by majacirkova1989** [comment]
Hm ok , but where to put this , in which file ????

**Comment by Nayjest** [comment]
In place where you add ExcelExport component
```php
...->addComponent(
    (new ExcelExport)->setIgnoredColumns([$columnName1, $columnName2])
)
```

**Comment by majacirkova1989** [comment]
okay thanks I solve it :)
