### ISSUE TITLE
Exclude columns in Excel Export

### ISSUE THREAD

**Issue by asaf050** [Nayjest/Grids#66]
How can I exclude for example "action" column in the excel export?
Thanks

**Comment by Nayjest** [comment]
Hi!
See 
```php
ExcelExport::setIgnoredColumns(array $ignoredColumns) // pass array of column names
```

**Comment by asaf050** [comment]
Thanks!

**Comment by prabukarana** [comment]
Can you more specific.

    new ExcelExport(),
     $ignore = array('Action');
    ->setIgnoredColumns($ignore)
               (new HtmlTag)
               ->setContent('<span class="glyphicon glyphicon-refresh"></span> Filter')
               ->setTagName('button')
               ->setRenderSection(RenderableRegistry::SECTION_END)
                ->setAttributes([
                      'class' => 'btn btn-success btn-sm'
                     ])
               ])
          ])


How to call it, please help

**Comment by wdog** [comment]
for example

```php
->setComponents([
    (new THead)
        ->setComponents([
             (new OneCellRow)
                 ->setComponents([

                     (new ExcelExport)->setIgnoredColumns(['price']),

                     (new HtmlTag)
                         ->setTagName('button')
                         ->setAttributes([
                            'type'  => 'submit',
                            'class' => 'btn btn-success btn-small',
                         ])
                         ->addComponent(new RenderFunc(function () {
                            return ' <i class="glyphicon glyphicon-refresh" ></i> Filter';
                         })),
...

**Comment by prabukarana** [comment]
Thanks bro. it works..
