### ISSUE TITLE
Using multiple grids on one page

### ISSUE THREAD

**Issue by Severance** [Nayjest/Grids#67]
Hi, I adore this plugin. I'm having trouble using multiple grids on one blade page though. I'm creating the Grid config in the controller function for the view and rendering them before I make the page, then echoing each grid out in bootstrap tabular format.

My issues seem to appear when I'm using pagination (It only works for the first grid) and any of the header components like CSV export or Excel export. 

Everything only seems to work for the first grid, while the others break with an exception, any idea how to differentiate them all or is there some tutorial on using multiple grid instances on one page? I've made use of GridViews using the Yii Framework before and got around any interactivity issues using PJAX.

Cheers!

**Comment by Severance** [comment]
Oh I'm using Laravel 4.2!

**Comment by Nayjest** [comment]
Hi!
It's strange that multiple grids doesn't works on same page, becouse it was designed to work so.

Do your grids have different names? (see GridConfig::setName())

Are $_GET parameters for xls & csv / pagination passed inside nested array 
($_GET[grid_name][param_name]) ?

I will check that there is no bugs related to multiple grids on same page and add example to demo. But unfortunately I can do that only tomorrow.

**Comment by wdog** [comment]
+1 for the new example to demo

**Comment by Nayjest** [comment]
Issue related to exporting data from first grid when page contain multiple grids fixed. Use v0.9.3

**Comment by Nayjest** [comment]
Example added:

http://grids-demo.herokuapp.com/demo/example6

https://github.com/Nayjest/grids-demo/blob/master/app/Http/Controllers/DemoController.php#L261

**Comment by Nayjest** [comment]
PJAX is really cool feature, if you are planning to implement it for nayjest/grids, share it to the community :)
