### ISSUE TITLE
Sql query

### ISSUE THREAD

**Issue by majacirkova1989** [Nayjest/Grids#68]
Hello i have this query :
select count(*) as aggregate from `contact` inner join `company` on `company`.`contact_id` = `contact`.`id` inner join `person` on `contact`.`id` = `person`.`contact_id` inner join `address` on `address`.`addressable_id` = `person`.`id` inner join `country` on `country`.`id` = `address`.`country_id` inner join `groupable` on `groupable`.`groupable_id` = `contact`.`id` inner join `group` on `groupable`.`group_id` = `group`.`id` inner join `contact_category` on `contact_category`.`contact_id` = `contact`.`id` inner join `category` on `category`.`id` = `contact_category`.`category_id` inner join `sending_rule` on `sending_rule`.`contact_id` = `contact`.`id` inner join `language` on `language`.`id` = `sending_rule`.`language_id` inner join `distribution` on `distribution`.`id` = `sending_rule`.`distribution_id` inner join `message_type` on `message_type`.`id` = `sending_rule`.`message_type_id` where `contact`.`deleted_at` is null or `categorys`.`category` = Impedit rem ratione qui dicta nisi. group by `contact`.`id`)

Here is my filter;
     (new CheckCategory)
                                        ->setName('category')
                                        ->setVariants($category_name)
                                        ->setFilteringFunc(
                                            function ($filter_fields_category, EloquentDataProvider $dp) {
                                                /** @var Illuminate\Database\Eloquent\Builder $builder */

                                                for ($i = 0; $i < count($filter_fields_category); $i++) {
                                                    $builder = $dp->getBuilder();
                                                    $builder->where('categorys.category', '=', $filter_fields_category[$i], 'or')           /*->groupBy('category.category')*/
                                                    ;
                                                }
                                            })
                                        ->setDefaultValue($filter_fields_category)

All i want to do is to remove group by `contact`.`id` . How to do that with make changes of builder ?
Thanks

**Comment by Nayjest** [comment]
Sorry, I have no fast answer.
$dataProvider->getBuilder() returns a Eloquent Query Builder instance, so further questions regarding usage of query builder is more relevant for Laravel forums.

**Comment by brigite** [comment]
How to Group By on EloquentDataProvider.
I have a query with joins and count,
and I want to group by id.
Thanx

**Comment by imerr** [comment]
You just need to add the grouping to your query and it should work just fine

**Comment by Nayjest** [comment]
@imerr thanks for assist
@brigite see Laravel documentation, you need to create query with joins and grouping using Eloquent facilities (as @imerr said) and then pass that query to EloquentDataProvider as constructor argument.
