### ISSUE TITLE
Add custom attributes to grid column

### ISSUE THREAD

**Issue by ahmadazimi** [Nayjest/Grids#70]
Hi there,

Currently I'm working on building new framework based on Larabel 5 which it is using Grid class. I need to access to the columns html attributes. For example ```class```, ```rel```, ```data-...``` and etc.

I found that you set ```class``` attribute of each cell in ```TableCell``` class based on cell name. Is there any way to pass custom attributes to Grid class for each clell?

**Comment by Nayjest** [comment]
Hi!
TableCell extends HtmlTag class, so see Nayjest\Grids\Components\HtmlTag::setAttributes(array $attributes)

**Comment by Nayjest** [comment]
Also, if you need override all table cells, you may use your custom class in \Nayjest\Grids\Components\Tr::renderCells()

**Comment by Nayjest** [comment]
And if you need override Tr class, see \Nayjest\Grids\GridConfig::setRowComponent(RenderableComponentInterface $rowComponent)

**Comment by ahmadazimi** [comment]
wow..

Thank you for complete solution :-)

**Comment by ahmadazimi** [comment]
Hi there,

I have a problem to hanlde your suggestions! Can you help me with an example?

```php
// using an array for grid config and an array of columns to generate grid columns
$this->config = new GridConfig($grid_config);
$this->config->setColumns($columns);
$grid = new NayjestGrid($this->config);
```

So, how can I access to the ```TableCell``` instances of a row in above example to call ```setAttributes``` method on it? Or how can I pass custom attributes to the ```TabelCell``` instance  via 
```GridConfig``` class or ```FieldConfig``` class?
