### ISSUE TITLE
Drag and drop of columns in nayjest data grid

### ISSUE THREAD

**Issue by maicka123** [Nayjest/Grids#74]
Hello , 
Is it possible to make drag and drop of columns in nayjest data grid ?

Thanks Maja

**Comment by Nayjest** [comment]
Hi!
Yes it's possible but it's not related to functionality of Grids package. Grids package is responsible for rendering HTML tables & filtering-sorting data. Drag & Drop functionality can be implemented using JavaScript & this doesn't requires a lot from Grids package (maybe just getting some HTML element id's).
