### ISSUE TITLE
ExcelExport & CSVExport in dropdown menu

### ISSUE THREAD

**Issue by icemanblas** [Nayjest/Grids#75]
Hi,

I want to use Export functionality, but I want to wrap the ExcelExport and CSVExport actions with bootstrap's dropdown menu, something like this:

```php
(new HtmlTag)
    ->setComponents([
        (new RenderFunc(function () {
             return
                      '<div class="dropdown">' .
                      '    <button class="btn btn-primary pull-left dropdown-toggle" data-toggle="dropdown">Export<span class="caret"></span></button>' .
                      '    <ul class="dropdown-menu">' .
                      '        <li>' .
                     // excel export action
                     (new ExcelExport),
                         (new ExcelExport)->setIgnoredColumns(['id']) .
                      '        </li>' .
                      '        <li>' .
                      // csv export action
                        (new CsvExport)->setIgnoredColumns(['id']) .
                      '        </li>' .
                      '    </ul>' .
                      '</div>';
         }))
    ]),
```
However, when I run the code, I get the following exception: "FatalErrorException in TComponentView.php line 31: Call to a member function getConfig() on a non-object".

I have little experience with Nayjest grid and I appreciate if you help me figure out this issue.

**Comment by Nayjest** [comment]
Hi!
First of all, export components must be attached to component tree.
So, instead of using RenderFunc, create your own class for rendering that stuff and attach export components using "setComponents" method.

Then, you need to override export component to provide different input parameters, becouse they share same. For example, all ExcelExport components uses ExcelExport::INPUT_PARAM, i. e. renders excel document if $_GET['xls'] exists. Therefore first export component will render document and next that have "inored_columns" specified, will be ignored.

**Comment by icemanblas** [comment]
Hi,
thanks for your reply. I'm able to create custom class ExportDropdown, but I need more detail on how to attach the 'ExcelExrport' and 'CsvExport' components. But, thanks anyway, this was very helpful.

Cheers

**Comment by Nayjest** [comment]
1. Create ExportDropdown class
2. Attach export components using `ExportDropdown::setComponents()` in place where you build grid (your controller or view).
3. Render children from ExportDropdown class using `ExportDropdown::renderComponents()`. The simplest way to render template -- override `ExportDropdown::render()` and somewhere in template call 'renderComponents()' method.

**Comment by icemanblas** [comment]
Thanks man,

I am able to solve this issue. Your guidance was very, very helpful.

Best regards

**Comment by Nayjest** [comment]
No problem, good luck with coding.
