### ISSUE TITLE
Drag and Drop Option for Row and fire an AJAX request

### ISSUE THREAD

**Issue by joshykp** [Nayjest/Grids#78]
Hi ,

It will be very useful and attractive if Nayjest grid has the option of 'Drag and Drop'  a row and fire an AJAX function if needed.

Please let me know, whether Nayjest has the above said facility exists or not.

**Comment by Nayjest** [comment]
Hi
No, grids have no such functionality. If you will implement it, I will appreciate sharing this component to community.
See https://github.com/view-components/grids for further development.
