### ISSUE TITLE
Pagination on Laravel 5 with the Nayjest grid does not work

### ISSUE THREAD

**Issue by meena-kasi-optus** [Nayjest/Grids#79]
Hi,

Thanks for the really nice report package. Wondering if you could help me with the issue below.

I seem to have an issue with the pagination not working in my report using Laravel 5.0 .

My report is displaying fine and the page numbers are also displayed fine.

However, when I click the paging links at the bottom, my URL looks like the below and does not change the record set:

http://app.local/report?report_grid%255Bpage%255D=3

The URL seems to have %255B and %255D which is causing the issue.

But, when I hover the mouse over the page numbers displayed on the pagination section, the URL is displayed correctly as  http://app.local/report?report_grid%5Bpage%5D=3.

Not sure why it changes after I click the page number.

Also, when I manually change my URL to http://app.local/report?report_grid%5Bpage%5D=4 the records are getting updated fine in the report grid.

Please could you let me know why , the URL changes to %255B and %255D instead of %5B and %5D ? Any help would be much appreciated.

Is there any way to use the report with POST rather than GET?

Below is my code:

<?php 
namespace App\Http\Controllers;
use App\User;
use App\MyData;
use Grids;
use Html;
use DB;
use Illuminate\Support\Facades\Config;
use Nayjest\Grids\Components\Base\RenderableRegistry;
use Nayjest\Grids\Components\ColumnHeadersRow;
use Nayjest\Grids\Components\ColumnsHider;
use Nayjest\Grids\Components\CsvExport;
use Nayjest\Grids\Components\ExcelExport;
use Nayjest\Grids\Components\Filters\DateRangePicker;
use Nayjest\Grids\Components\FiltersRow;
use Nayjest\Grids\Components\HtmlTag;
use Nayjest\Grids\Components\Laravel5\Pager;
use Nayjest\Grids\Components\OneCellRow;
use Nayjest\Grids\Components\RecordsPerPage;
use Nayjest\Grids\Components\RenderFunc;
use Nayjest\Grids\Components\ShowingRecords;
use Nayjest\Grids\Components\TFoot;
use Nayjest\Grids\Components\THead;
use Nayjest\Grids\Components\TotalsRow;
use Nayjest\Grids\DbalDataProvider;
use Nayjest\Grids\EloquentDataProvider;
use Nayjest\Grids\FieldConfig;
use Nayjest\Grids\FilterConfig;
use Nayjest\Grids\Grid;
use Nayjest\Grids\GridConfig;

class ReportController extends Controller
{     

    public function getReport()
    {
        $grid = new Grid(
            (new GridConfig)
                ->setDataProvider(
                    new EloquentDataProvider(MyData::query())
                )
                ->setName('report_grid')
                ->setPageSize(5)
                ->setColumns([
                    (new FieldConfig)
                        ->setName('id')
                        ->setLabel('ID')
                        ->setSortable(true)
                        ->setSorting(Grid::SORT_ASC)
                    ,
                    (new FieldConfig)
                        ->setName('first_name')
                        ->setLabel('First Name')
                        ->setSortable(true)                        
                        ->setCallback(function ($val) {
                            return "{$val}";
                        })                       
                        ->addFilter(
                            (new FilterConfig)
                                ->setOperator(FilterConfig::OPERATOR_LIKE)
                        )
                    ,
                    (new FieldConfig)
                        ->setName('email')
                        ->setLabel('Email')
                        ->setSortable(true)
                        ->setCallback(function ($val) {                   
                            return
                                '<small>'                             
                                . HTML::link("mailto:$val", $val)
                                . '</small>';
                        })
                        ->addFilter(
                            (new FilterConfig)
                                ->setOperator(FilterConfig::OPERATOR_LIKE)
                        )
                    ,             
                    (new FieldConfig)
                        ->setName('work_phone')
                        ->setLabel('Work Phone')
                        ->setSortable(true)
                        ->addFilter(
                            (new FilterConfig)
                                ->setOperator(FilterConfig::OPERATOR_LIKE)
                        )
                    ,
                    (new FieldConfig)
                        ->setName('mobile')
                        ->setLabel('Mobile')
                        ->setSortable(true)
                        ->addFilter(
                            (new FilterConfig)
                                ->setOperator(FilterConfig::OPERATOR_LIKE)
                        )
                    ,
                    (new FieldConfig)
                        ->setName('emp_no')
                        ->setLabel('Emp No')
                        ->setSortable(true)
                        ->addFilter(
                            (new FilterConfig)
                                ->setOperator(FilterConfig::OPERATOR_LIKE)
                        )
                    ,                  
                    (new FieldConfig)
                        ->setName('team')
                        ->setLabel('Team')
                        ->setSortable(true)
                        ->addFilter(
                            (new FilterConfig)
                                ->setOperator(FilterConfig::OPERATOR_LIKE)
                        )
                    ,
                    (new FieldConfig)
                        ->setName('pos_title')
                        ->setLabel('Title')
                        ->setSortable(true)
                        ->addFilter(
                            (new FilterConfig)
                                ->setOperator(FilterConfig::OPERATOR_LIKE)
                        )
                    ,
                    (new FieldConfig)
                        ->setName('created_at')
                        ->setLabel('Created At')
                        ->setSortable(true)
                        ->addFilter(
                            (new FilterConfig)
                                ->setOperator(FilterConfig::OPERATOR_LIKE)
                        )                        
                    ,
                ])
                ->setComponents([
                    (new THead)
                        ->setComponents([
                            (new ColumnHeadersRow),
                            (new FiltersRow),
                            (new OneCellRow)
                                ->setRenderSection(RenderableRegistry::SECTION_END)
                                ->setComponents([
                                     #Control for specifying quantity of records displayed on page 
                                     (new RecordsPerPage)
                                        ->setVariants([
                                            5,
                                            50,
                                            100,
                                            1000
                                        ])
                                    ,
                                    # Control to show/hide rows in table
                                    (new ColumnsHider),
                                    (new CsvExport)
                                        ->setFileName('my_report' . date('Y-m-d'))
                                    ,
                                    new ExcelExport(),
                                    (new HtmlTag)
                                        ->setContent('<span class="glyphicon glyphicon-refresh"></span> Filter')
                                        ->setTagName('button')
                                        ->setRenderSection(RenderableRegistry::SECTION_END)
                                        ->setAttributes([
                                            'class' => 'btn btn-success btn-sm'
                                        ])
                                ])
                        ])
                    ,
                   
                    (new TFoot)
                        ->setComponents([                          
                           (new OneCellRow)
                            ->addComponents([
                                new Pager,
                                (new HtmlTag)
                                    ->setAttributes(['class' => 'pull-right'])
                                    ->addComponent(new ShowingRecords)
                                ,
                            ])
                        ])
                    ,
                                            
                ])

        );
        $grid = $grid->render();
        return view('report.default', compact('grid'));
    }

}

Thank you.

**Comment by icemanblas** [comment]
Hi, I don't have issue with the pagination itself, but I want to be able to use POST. Is there a way to do that?

Thanks, Blashko

**Comment by Nayjest** [comment]
@icemanblas regarding $_POST, it's possible if you will override inputProcessor class, but therefore you will need to save filter's state somewhere (session, cookies, local storage, etc. session looks like best place for that), becouse pagination and other controls that changes URL will reset it.

**Comment by Nayjest** [comment]
See https://github.com/Nayjest/Grids/issues/76
Fixed in v0.9.8

Please confirm that fix works for you.
