### ISSUE TITLE
Pagination not work with filters

### ISSUE THREAD

**Issue by maicka123** [Nayjest/Grids#81]
Hey , I have filters with checkboxes class above the grid table and when i use that filtration it is not working in grid , in the url when i click on the next page the previous data is not kept, , for example when i make filtration i got this url:

http://project.dev/contacts?checkbox_country%5B%5D=United+States&checkbox_country%5B%5D=Canada&checkbox_country%5B%5D=Afghanistan&checkbox_country%5B%5D=Albania&checkbox_country%5B%5D=Algeria&checkbox_country%5B%5D=Antigua+and%2For+Barbuda&checkbox_country%5B%5D=Argentina&checkbox_country%5B%5D=Armenia&checkbox_country%5B%5D=Australia&checkbox_country%5B%5D=Austria&checkbox_country%5B%5D=Azerbaijan&checkbox_country%5B%5D=Bahamas&checkbox_country%5B%5D=Bahrain&checkbox_country%5B%5D=Bangladesh&checkbox_country%5B%5D=Barbados&checkbox_country%5B%5D=Belarus&checkbox_country%5B%5D=Belgium&checkbox_country%5B%5D=Belize&checkbox_country%5B%5D=countryless&checkbox_sending_rules%5B%5D=Email_Press+Release_en&checkbox_sending_rules%5B%5D=SMS_Press+Release_mk&checkbox_sending_rules%5B%5D=Fax_Press+Release_ru&checkbox_sending_rules%5B%5D=Email_Press+Release_mk&checkbox_sending_rules%5B%5D=Email_Press+Release_ru&checkbox_sending_rules%5B%5D=Email_Press+Release_cr&checkbox_sending_rules%5B%5D=Email_Press+Release_si&checkbox_sending_rules%5B%5D=SMS_Press+Release_ru&checkbox_sending_rules%5B%5D=SMS_Press+Release_cr&checkbox_sending_rules%5B%5D=SMS_Press+Release_si&checkbox_sending_rules%5B%5D=Fax_Press+Release_mk&checkbox_sending_rules%5B%5D=Fax_Press+Release_cr&checkbox_sending_rules%5B%5D=Fax_Press+Release_si&checkbox_sending_rules%5B%5D=Fax_Invitation_ru&checkbox_sending_rules%5B%5D=Email_Invitation_en&checkbox_sending_rules%5B%5D=SMS_Invitation_mk&checkbox_sending_rules%5B%5D=Email_Invitation_mk&checkbox_sending_rules%5B%5D=Email_Invitation_ru&checkbox_sending_rules%5B%5D=Email_Invitation_cr&checkbox_sending_rules%5B%5D=Email_Invitation_si&checkbox_sending_rules%5B%5D=SMS_Invitation_ru&checkbox_sending_rules%5B%5D=SMS_Invitation_cr&checkbox_sending_rules%5B%5D=SMS_Invitation_si&checkbox_sending_rules%5B%5D=Fax_Invitation_mk&checkbox_sending_rules%5B%5D=Fax_Invitation_cr&checkbox_sending_rules%5B%5D=Fax_Invitation_si&checkbox_sending_rules%5B%5D=Fax_Newsletter_en&checkbox_sending_rules%5B%5D=Fax_Newsletter_ru&checkbox_sending_rules%5B%5D=Email_Newsletter_en&checkbox_sending_rules%5B%5D=SMS_Newsletter_mk&checkbox_sending_rules%5B%5D=Email_Newsletter_mk&checkbox_sending_rules%5B%5D=Email_Newsletter_ru&checkbox_sending_rules%5B%5D=Email_Newsletter_cr&checkbox_sending_rules%5B%5D=Email_Newsletter_si&checkbox_sending_rules%5B%5D=SMS_Newsletter_ru&checkbox_sending_rules%5B%5D=SMS_Newsletter_cr&checkbox_sending_rules%5B%5D=SMS_Newsletter_si&checkbox_sending_rules%5B%5D=Fax_Newsletter_mk&checkbox_sending_rules%5B%5D=Fax_Newsletter_cr&checkbox_sending_rules%5B%5D=Fax_Newsletter_si&checkbox_sending_rules%5B%5D=Email_Other_en&checkbox_sending_rules%5B%5D=SMS_Other_mk&checkbox_sending_rules%5B%5D=Email_Other_mk&checkbox_sending_rules%5B%5D=Email_Other_ru&checkbox_sending_rules%5B%5D=Email_Other_cr&checkbox_sending_rules%5B%5D=Email_Other_si&checkbox_sending_rules%5B%5D=SMS_Other_ru&checkbox_sending_rules%5B%5D=SMS_Other_cr&checkbox_sending_rules%5B%5D=SMS_Other_si&checkbox_sending_rules%5B%5D=Fax_Other_mk&checkbox_sending_rules%5B%5D=Fax_Other_ru&checkbox_sending_rules%5B%5D=Fax_Other_cr&checkbox_sending_rules%5B%5D=Fax_Other_si&checkbox_sending_rules%5B%5D=sendless&checkbox_category%5B%5D=Itaque+autem+rerum+doloremque+omnis+voluptas+distinctio+earum.&checkbox_category%5B%5D=Voluptatem+saepe+dolor+cumque+minus.&checkbox_category%5B%5D=Sit+cumque+earum+minima+placeat+voluptatem+debitis.&checkbox_category%5B%5D=Et+doloribus+et+est.&checkbox_category%5B%5D=Temporibus+sint+impedit+ipsum+ea+eos+fugit.&checkbox_category%5B%5D=Repellat+labore+sed+nostrum+aut.&checkbox_category%5B%5D=Nulla+corporis+architecto+laudantium+labore+quis.&checkbox_category%5B%5D=Sint+ex+quibusdam+et+numquam+aspernatur+qui+et+nulla.&checkbox_category%5B%5D=Mollitia+et+explicabo+temporibus+accusamus.&checkbox_category%5B%5D=Dolor+reiciendis+delectus+et+cum+quis+esse.&checkbox_category%5B%5D=categoryless&checkbox_group%5B%5D=Eum+quisquam+maiores+et+similique+ut.&checkbox_group%5B%5D=Ex+ducimus+ullam+neque+qui.&checkbox_group%5B%5D=fsdfsdf&checkbox_group%5B%5D=Nihil+qui+aut+minus+et+illum+est+voluptate.&checkbox_group%5B%5D=Odit+accusamus+ipsum+amet+nam+et+animi+autem.&checkbox_group%5B%5D=Quia+maxime+omnis+ad+est+voluptatem.&checkbox_group%5B%5D=Rem+illum+aliquam+beatae+quo+minus+sint+dignissimos+eum.&checkbox_group%5B%5D=Repudiandae+reprehenderit+voluptas+et+optio.&checkbox_group%5B%5D=Vel+laudantium+doloremque+asperiores+molestiae.&filter_submit=Filter&checkbox_group%5B%5D=Eum+quisquam+maiores+et+similique+ut.&checkbox_group%5B%5D=Ex+ducimus+ullam+neque+qui.&checkbox_group%5B%5D=fsdfsdf&checkbox_group%5B%5D=Nihil+qui+aut+minus+et+illum+est+voluptate.&checkbox_group%5B%5D=Odit+accusamus+ipsum+amet+nam+et+animi+autem.&checkbox_group%5B%5D=Quia+maxime+omnis+ad+est+voluptatem.&checkbox_group%5B%5D=Rem+illum+aliquam+beatae+quo+minus+sint+dignissimos+eum.&checkbox_group%5B%5D=Repudiandae+reprehenderit+voluptas+et+optio.&checkbox_group%5B%5D=Vel+laudantium+doloremque+asperiores+molestiae.&contacts_grid%5Bfilters%5D%5Brecords_per_page%5D=5&contacts_grid%5Bfilters%5D%5Bcontact.id-like%5D=&contacts_grid%5Bfilters%5D%5Bgroup-like%5D=&contacts_grid%5Bfilters%5D%5Bcontact.email-like%5D=&contacts_grid%5Bfilters%5D%5Bcontact.phone_number-like%5D=&contacts_grid%5Bfilters%5D%5Bcountry.country-like%5D=&contacts_grid%5Bfilters%5D%5Bcompany-like%5D=&contacts_grid%5Bfilters%5D%5Bcategory-like%5D=&contacts_grid%5Bfilters%5D%5Bsending_options-like%5D=

When i go on the next page i got this:
http://project.dev/contacts?contacts_grid%5Bfilters%5D%5Brecords_per_page%5D=5&contacts_grid%5Bfilters%5D%5Bcontact.id-like%5D=&contacts_grid%5Bfilters%5D%5Bgroup-like%5D=&contacts_grid%5Bfilters%5D%5Bcontact.email-like%5D=&contacts_grid%5Bfilters%5D%5Bcontact.phone_number-like%5D=&contacts_grid%5Bfilters%5D%5Bcountry.country-like%5D=&contacts_grid%5Bfilters%5D%5Bcompany-like%5D=&contacts_grid%5Bfilters%5D%5Bcategory-like%5D=&contacts_grid%5Bfilters%5D%5Bsending_options-like%5D=&contacts_grid%5Bpage%5D=2

Can u tell me how to solve this ?
And is it possible to get shortest url  ?
Thanks Maja

**Comment by Nayjest** [comment]
See https://github.com/Nayjest/Grids/issues/76
Fixed in v0.9.8

Please confirm that fix works for you.

**Comment by Nayjest** [comment]
>> And is it possible to get shortest url ?

Use $grid->setName()  to give a shorter grid name, you can also use $filter->setName() for giving shorter names to filters.

I can suggest another improvement: you can implement JavaScript, that will remove empty inputs before submit. If you will do so, I will appreciate any contributions (pull requests, send code snippets, etc)

**Comment by maicka123** [comment]
Thanks anyway , i solve it with the array from the grid i just put inside
the main array name of filters and now is working :)

**Comment by Nayjest** [comment]
@maicka123 thanks for your response and sorry that this issue waited for solution so long.
