### ISSUE TITLE
Add css class to row if condition is met

### ISSUE THREAD

**Issue by icemanblas** [Nayjest/Grids#82]
Hi,

I'm sorry if this is duplicate issue or it already has an answer, but I need quick solution for this. I want to append class to the parent row, if a condition is met for one of the attributes. Let me visualise this:

id | status
------------ | -------------
1 | ok
2 | ok
**3** | **error**
4 | ok
**5** | **error**

So, all rows containing 'status' => 'error', should have class appended to. How am I supposed to do that?

Thanks in advance

**Comment by wdog** [comment]
see issue #48

**Comment by wdog** [comment]
just create this class 

```php
class ErrorTr extends \Nayjest\Grids\Components\Tr
{
  public function getTagName() { return 'tr'; }

  public function getAttributes()
  {
    // suppose you want to match the string 'error' from a field/cell named 'error'
    $error = $this->getDataRow()->getCellValue('error');
    $errorClass = ( $error == 'error' ) ? 'error-class': 'other-class';
    $newAttributes = ['class' => $errorClass];
    return array_merge(parent::getAttributes(), $newAttributes);
  }
}
```

and add the component to the gridconfig

```php

$gridConfig = (new GridConfig)
  ->setName('servizi')
  ->setColumns([
  ...
  ])
  ->setComponents([
  ...
  ]);
// here the magic part!
$gridConfig->setRowComponent(new ErrorTr());
$grid = new Grid($gridConfig);
$grid = $grid->render();

```
