### ISSUE TITLE
Add Records Per Page?

### ISSUE THREAD

**Issue by advisor-** [Nayjest/Grids#84]
In Basic example

$cfg = [
    'src' => 'App\User',
    'columns' => [
            'id',
            'name',
            'email',
            'country'
    ]
];
echo Grids::make($cfg);

how can I set  RecordsPerPage?

**Comment by advisor-** [comment]
$grid->getConfig()->getDataProvider()->setPageSize(10);

**Comment by Nayjest** [comment]
Hi!
Sorry for late response, I was on vacation. Your solution is absolutely correct. Also you can use \Nayjest\Grids\Components\RecordsPerPage component to allow users to set this parameter manually.

**Comment by advisor-** [comment]
Thanks for your reply...
I can set the Variants using the mentioned component, but how can use it to set the page size ?

**Comment by Nayjest** [comment]
Just add RecordsPerPage component, it will render select input with variants and call $grid->getConfig()->getDataProvider()->setPageSize() with selected value if user will specify it.
