### ISSUE TITLE
Grid column size

### ISSUE THREAD

**Issue by wdog** [Nayjest/Grids#85]
Hi
It's there a way to set column width to a fixed value?

thanks

**Comment by Nayjest** [comment]
Hi!
Yes, see src/Components/TableCell.php it extends HtmlTag and HtmlTag class has setAttributes() method.

**Comment by Nayjest** [comment]
Also each column has 'column-<name>' class, so you can just add CSS

**Comment by wdog** [comment]
thanks i've used the column- class

here an example to help future readers

``` php
 (new FieldConfig)
            ->setName('price')
            ->setLabel('Price')
            ->addFilter(
              (new FilterConfig)
                ->setName(price')
                ->setOperator(FilterConfig::OPERATOR_EQ)
            )
```

and then 

``` css
<style>
.column-price {
  width: 100px;
  text-align: right;
}
</style>
````

and it works! thanks

but there's no way to pass attributes via  (new FieldConfig), maybe in the future you can add the setAttribute to the FieldConfig  and pass it to the TableCell.

**Comment by Nayjest** [comment]
>> but there's no way to pass attributes via (new FieldConfig), maybe in the future you can add the setAttribute to the FieldConfig and pass it to the TableCell.

It's already possible in my drafts of Grids 2 (not released yet), but there will be a hard migration to new version (significant API changes)

**Comment by Nayjest** [comment]
See [presentation-framework/grids](https://github.com/presentation-framework/grids) if you are interested in further development. Contributions are welcome :)

**Comment by jpldev** [comment]
Is there a way to let the user change manually the width of the column?
