### ISSUE TITLE
Case insensitive LIKE operator in FilterConfig

### ISSUE THREAD

**Issue by leoquijano** [Nayjest/Grids#93]
Hi,

Is it possible to add a case insensitive LIKE operator to the Grid's filtering system? I noticed there is support for the standard operators, but there's no support for PostgreSQL's ILIKE operator.

I know it's a proprietary operator. In my case it wouldn't be a problem because I'm not planning to move away from PostgreSQL (and moving away in any case is not a simple thing). But if portability is an issue, is there a way to add custom operators to a filter, so the programmer can just specify whatever he would like?

I could do this:

```php
$filter = new FilterConfig();
$filter->setOperator("ilike");
...
```

But the value itself won't get wrapped in % signs, so it wouldn't work like the LIKE operator.
Any thoughts?

**Comment by leoquijano** [comment]
Small workaround, though case insensitivity is so common it'd still be nice to have this, or a similar approach, in the code base.

This will return a ILIKE filter for the specified field:

```php
function getFilterILike($name) {
  $filter = new FilterConfig();
  $filter->setName($name);
  $filter->setFilteringFunc(function($value, $dataProvider) use ($name) {
    if(!is_null($value) && !empty($value)) {
      $value = addcslashes($value, '_%\\');
      $value = "%$value%";
      $dataProvider->filter($name, "ilike", $value);
    }
  });
  return $filter;
}
```

(Note that the issue described in #94 is already fixed here)

**Comment by Nayjest** [comment]
Hi!
Thanx for reporting this issue.
It's possible to implement case insensitive like without usage of proprietary ILIKE:

```sql
WHERE LOWER(some_field_selector) LIKE LOWER('%value%')
```

Currently I'm not implementing new features in this repository, development moved to:
https://github.com/presentation-framework/presentation-framework
https://github.com/presentation-framework/grids

Also I created issue: https://github.com/presentation-framework/presentation-framework/issues/16

Currently you can continue using Filter::setFilteringFunc()  or implement your components with support of 'ilike'.
If you want to contribute, you are welcome, I will accept pull-request with approach that doesn't uses proprietary 'ilike' (as I described in SQL snippet above) in this repository or https://github.com/presentation-framework/presentation-framework (it's actually in pre-alpha state).

**Comment by leoquijano** [comment]
Thanks!

Ok for my current project I think I will continue to use setFilteringFunc. But I set the "watch" option to your new repo so I can track it for future projects. Maybe I can contribute there.
