### ISSUE TITLE
Custom data provider (e.g. for REST/SOAP-backend API)

### ISSUE THREAD

**Issue by geraldb-nicat** [Nayjest/Grids#95]
hi there!

first of all many thanks for your work on this package!

i have one question though: is it possible to use this package to realize server-side processing (paging/filtering/sorting) of data, that comes from a server-side REST- or SOAP-backend?

i can see, that the package supports php-arrays as a data provider. but that would mean, i have to get all the rows from the backend first, and then filter/sort this on the webserver. but if the REST/SOAP-backend supports paging/sorting by itself, it would be great, if there was a way for Nayjest/Grids to forward/map it's requests to this API.

if there is currently no way of achieving this, i guess this would be a great enhancement. maybe it could be realized as some kind of Custom Data Provider, that implements functions to map the data-processing variables and calls to the custom backend API.

i think cartalyst has a similar feature called "Custom Data Handlers" (see here: https://cartalyst.com/manual/data-grid/3.0#custom-data-handlers) - although i must admit, i have never worked with cartalyst.

many thanks in advance for your help!

best wishes
gerald

**Comment by Nayjest** [comment]
Hi!
Yep, it's designed to be extendable this way. You can create your custom DataProvider as described.

1. It would be easy to override DataProvider::filter for specifying API request parameters.
2. Regarding pagination -- it can be little bit more difficult becouse DataProvider uses \Illuminate\Pagination\Paginator class and I suggest here some difficulties.
3. Not sure that DataProviders will currently work with arrays at all, becouse this functionality isn't tested. I have only few acceptance tests for https://github.com/Nayjest/grids-demo that works via Eloquent or Doctrine/DBAL

It's important to mention thay development of nayjest/grids is moved to 
[presentation/grids](https://github.com/presentation-framework/grids) and [presentation/framework](https://github.com/presentation-framework/presentation-framework)

Currently there is no issues with using arrays as data source (during development I use ArrayDataProvider in wabapp for acceptance tests), but no bindings to Eloquent & Doctrine/DBAL.

Presentation/framework is written from scratch and DataProviders there is totally refactored and it would be more easy to implement features that you want.
* There are classes for describing operations (pagination, filter, sorting, see it [here](https://github.com/presentation-framework/presentation-framework/tree/master/src/Data/Operation))
* There are classes that applies operation to data sources: see it [here](https://github.com/presentation-framework/presentation-framework/tree/master/src/Data/Processor)

If you will use [presentation/grids](https://github.com/presentation-framework/grids) and [presentation/framework](https://github.com/presentation-framework/presentation-framework), you have a possibily to make a great contribution sharing your basic class for REST API data provider :)

**Comment by Nayjest** [comment]
Also, if you want to contribute, please contact me (email: mail@vitaliy.in, Skype ID: vitaliy.step) and I will do what I can to help.

**Comment by geraldb-nicat** [comment]
@Nayjest 
many thanks for the extensive info!

i'd really like to contribute, but the REST-calls are already handled by a custom and rather specific implementation, that does all the HTTP-communication already. i'd just call the methods of that API to get the data. so i'd need to forward the datagrid calls to the corresponding methods of that custom API-class. so i don't think, that would be publically helpful.

but i will take a look at presentation/grids and see if i can achieve my goal with that package. many thanks again!
