### ISSUE TITLE
Printer friendly export

### ISSUE THREAD

**Issue by XaphanBael** [Nayjest/Grids#96]
Hi,

First of all thanks for the awesome package. However i do have a question, is it possible to generate a printer friendly view based on the grid results (similair to the excel and csv export).

**Comment by Nayjest** [comment]
Hi!
Sure it's possible, you need to take [CsvExport component](https://github.com/Nayjest/Grids/blob/master/src/Components/CsvExport.php) as a base and create your own class that will use any lib for PDF generation.

**Comment by XaphanBael** [comment]
Thanks, i'll take a look at that.

Quick second question though, is there a way for me to change the order of filters without changing the field order itself? For instance, my grid has 15 fields, only 3 of them have filters, i would like all three filters to be aligned on the left side of the page instead of "above" their own column.

**Comment by Nayjest** [comment]
Here is an example of filters that is not linked to columns.
```php
$config->setComponents([
            (new THead())
                ->addComponent(
                    (new OneCellRow)
                        ->addComponents([
                            (new Filter)
                                ->setName('from')
                                ->setLabel('Dates:')
                                ->setTemplate('*.components.filters.date_picker')
                                ->setDefaultValue($defaultFrom)
                            ,
                            (new Filter)
                                ->setName('to')
                                ->setLabel('&mdash;&nbsp;&nbsp;')
                                ->setTemplate('*.components.filters.date_picker')
                                ->setDefaultValue($defaultTo)
                            ,
```
